// СГЕНЕРИРОВАНО из shared/copy/keys.tsv — не редактировать вручную.
// Регенерация: npm run build:copy (см. shared/copy/README.md).
export const RU: Record<string, string> = {
  'app.tagline': 'ТРЕНАЖЁР РЕШЕНИЙ · НЕ БИРЖА',
  'app.disclaimer': 'Игра не даёт торговых сигналов и не обещает дохода. Внутриигровые ресурсы не выводятся.',
  'app.loading': 'Загрузка архива рыночных катастроф…',
  'nav.home': 'ГЛАВНАЯ',
  'nav.academy': 'ОБУЧЕНИЕ',
  'nav.arena': 'ПРАКТИКА',
  'nav.bestiary': 'УГРОЗЫ',
  'nav.more': 'ЕЩЁ',
  'shell.scenarioProgress': 'СЦЕНАРИЙ',
  'shell.protocol': 'ПРАВИЛО',
  'arena.brief': 'БРИФИНГ',
  'arena.task': 'ЗАДАЧА',
  'arena.skills': 'КАРТЫ НАВЫКОВ',
  'arena.decisions': 'РЕШЕНИЕ',
  'arena.confirm': 'ЗАФИКСИРОВАТЬ РЕШЕНИЕ',
  'arena.confirmHint': 'Будущее скрыто. После фиксации — раскроем архив.',
  'arena.step2': 'ВТОРОЙ ШАГ',
  'arena.futureHidden': 'БУДУЩЕЕ СКРЫТО',
  'arena.t0': 't0 · ТОЧКА РЕШЕНИЯ',
  'arena.unskill': 'СНЯТЬ КАРТУ',
  'arena.pause': 'ПАУЗА',
  'arena.exit': 'ПОКИНУТЬ СЦЕНАРИЙ',
  'arena.exitHint': 'Рынок подождёт. Он вообще никуда не торопится.',
  'reveal.title': 'АРХИВ РАСКРЫТ',
  'reveal.play': 'ПРОКРУТИТЬ ПОСЛЕДСТВИЯ',
  'reveal.fact': 'РЫНОЧНЫЙ ФАКТ',
  'reveal.consequence': 'ПОСЛЕДСТВИЕ ДЕЙСТВИЯ',
  'reveal.quality': 'КАЧЕСТВО РЕШЕНИЯ',
  'reveal.next': 'СЛЕДУЮЩАЯ ОХОТА',
  'reveal.review': 'РАЗБОР',
  'reveal.rule': 'ПЕРЕНОСИМОЕ ПРАВИЛО',
  'verdict.agree': 'РЫНОК СОГЛАСИЛСЯ. ЭТО НЕ ЗНАЧИТ, ЧТО ТЫ БЫЛ ПРАВ.',
  'verdict.disagree': 'РЫНОК НЕ СОГЛАСИЛСЯ. ЭТО НЕ ЗНАЧИТ, ЧТО ТЫ ОШИБСЯ.',
  'states.loading': 'ЗАГРУЗКА ДАННЫХ',
  'states.loadingSub': 'Рынок ищет оправдание. Подожди.',
  'states.offline': 'СВЯЗИ НЕТ',
  'states.offlineSub': 'Хорошая новость: рынок тоже никуда не убежал.',
  'states.locked': 'ЗАПЕРТО',
  'states.lockedSub': 'Сущность пока считает тебя недостаточно удобной жертвой.',
  'states.error': 'ДАННЫЕ НЕ ЗАГРУЖЕНЫ',
  'states.errorSub': 'Даже сервер иногда делает вид, что всё под контролем.',
  'states.retry': 'ПОВТОРИТЬ',
  'states.empty': 'ЗДЕСЬ ПОКА ПУСТО',
  'states.emptySub': 'Даже паника начинается с чистого листа.',
  'states.saved': 'РЕЗУЛЬТАТ СОХРАНЁН',
  'states.savedSub': 'Теперь ошибка официально принадлежит истории.',
  'states.noTrade': 'ВНЕ РЫНКА',
  'states.noTradeSub': 'Сделка не открыта. Паника тоже.',
  'academy.title': 'АКАДЕМИЯ',
  'academy.chapters': 'ГЛАВЫ',
  'academy.sub': 'Теория объясняет принцип. Практика проверяет, применил ли ты его в шуме.',
  'bestiary.title': 'УГРОЗЫ',
  'bestiary.sub': 'Сущность — не враг, которого убивают. Это давление, которое не пускают в решение.',
  'journal.title': 'ЖУРНАЛ РЕШЕНИЙ',
  'journal.sub': 'Не свиток ошибок, а история: паттерны, сильные навыки, слабые зоны.',
  'tournament.title': 'ТУРНИРЫ',
  'tournament.sub': 'Один набор данных на всех. Победа — по качеству, скорость — только tie-break.',
  'market.title': 'МАРКЕТ',
  'market.sub': 'Косметика и контент. Ответы, оценки и риск-лимиты не продаются.',
  'profile.title': 'ПРОФИЛЬ',
  'more.title': 'ЕЩЁ',
  'settings.title': 'НАСТРОЙКИ',
  'settings.sound': 'ЗВУК',
  'settings.reduceMotion': 'МЕНЬШЕ ДВИЖЕНИЯ',
  'settings.language': 'ЯЗЫК',
  'home.title': 'ГЛАВНАЯ',
  'home.continue': 'ПРОДОЛЖИТЬ ОХОТУ',
  'home.daily': 'СЕГОДНЯ В АРХИВЕ',
  'common.back': 'НАЗАД',
  'common.close': 'ЗАКРЫТЬ',
  'common.retry': 'ПОВТОРИТЬ',
  'home.greet': 'Архив катастроф открыт. Выбирай, где сегодня ошибаться со вкусом.',
  'home.resume': 'ПРОДОЛЖИТЬ СЦЕНАРИЙ',
  'home.start': 'НАЧАТЬ ОХОТУ',
  'home.scenarios': 'СЦЕНАРИИ',
  'home.sections': 'РАЗДЕЛЫ',
  'home.best': 'ЛУЧШЕЕ',
  'academy.topic': 'ТЕМА',
  'academy.train': 'ТРЕНИРОВАТЬ В АРЕНЕ',
  'academy.linked': 'СВЯЗАННЫЕ НАВЫКИ',
  'academy.ch.risk.title': 'Риск: размер имеет значение',
  'academy.ch.risk.body': 'Риск определяется до входа: доля депозита, стоп, условие отмены. Рынок платит тем, кто переживает ошибки, а не тем, кто их избегает.',
  'academy.ch.structure.title': 'Структура: читай следы, а не свечи',
  'academy.ch.structure.body': 'Уровень, пробой, ретест, объём. Отдельная свеча врёт; структура из трёх событий врёт реже. Подтверждение обязательно.',
  'academy.ch.tf.title': 'Таймфреймы: старшие решают',
  'academy.ch.tf.body': 'Младший таймфрейм показывает шум красиво. Направление и уровни бери со старшего, точку входа — с младшего.',
  'academy.ch.noise.title': 'Шум: карантин для новостей',
  'academy.ch.noise.body': 'Заголовок — это эмоция с дедлайном. Новость уходит в карантин на сессию; решение — только по структуре и объёму.',
  'academy.ch.discipline.title': 'Дисциплина: система больше сделки',
  'academy.ch.discipline.body': 'Зелёная сделка мимо плана — красный флаг. Пауза после убытка, журнал, запрет на revenge: скучно, прибыльно, обязательно.',
  'academy.ch.plan.title': 'План: отмена пишется заранее',
  'academy.ch.plan.body': 'У каждой идеи есть условие «я неправ»: цена, время, событие. Нет условия отмены — нет идеи, есть надежда.',
  'bestiary.tell': 'ПРИЗНАК',
  'bestiary.counter': 'КОНТР-ПРИЁМ',
  'bestiary.train': 'ОХОТИТЬСЯ В АРЕНЕ',
  'bestiary.mastered': 'ОСВОЕНА',
  'bestiary.seen': 'ЗАМЕЧЕНА',
  'journal.patterns': 'ПОВТОРЯЮЩИЕСЯ ПАТТЕРНЫ',
  'journal.history': 'ИСТОРИЯ РЕШЕНИЙ',
  'journal.repeat': 'РЕКОМЕНДАЦИИ ПО ПОВТОРУ',
  'journal.best': 'ЛУЧШЕЕ КАЧЕСТВО',
  'journal.fix': 'ИСПРАВЛЕНИЕ',
  'journal.empty': 'Пока пусто: пройди первый сценарий, и журнал начнёт коллекционировать твои паттерны.',
  'tourn.join': 'ВОЙТИ',
  'tourn.joined': 'ТЫ ВНУТРИ',
  'tourn.board': 'ЛИДЕРБОРД',
  'tourn.you': 'ТЫ',
  'tourn.note': 'Асинхронно: один набор данных на всех, победа по качеству. Скорость — только tie-break.',
  'tourn.rookie.title': 'ПЕСОЧНИЦА: ПЕРВАЯ КРОВЬ',
  'tourn.rookie.body': 'Два архивных сценария. Идеально для калибровки прицела.',
  'tourn.risk.title': 'КУБОК ХОЛОДНОЙ ГОЛОВЫ',
  'tourn.risk.body': 'Протокол «Сначала риск». Гоблины плеча не допускаются.',
  'market.buy': 'КУПИТЬ',
  'market.owned': 'КУПЛЕНО',
  'market.balance': 'БАЛАНС',
  'market.noFunds': 'Не хватает кредитов. Арена платит за качество, а не за надежду.',
  'market.bought': 'Куплено. Косметика не влияет на качество решений — только на стиль поражения.',
  'market.i.theme-neon.title': 'Тема «Неоновая свалка»',
  'market.i.theme-neon.body': 'Косметическая тема интерфейса. Кислоты станет больше, ошибок — нет.',
  'market.i.avatar-golem.title': 'Аватар «Голем-якорь»',
  'market.i.avatar-golem.body': 'Тяжёлый силуэт для профиля. К старой цене больше не приковывает.',
  'market.i.season1.title': 'Сезонный набор «Паника-99»',
  'market.i.season1.body': 'Рамки и фоны сезона. Паника коллекционная, убытки — нет.',
  'profile.stats': 'СТАТИСТИКА',
  'profile.ach': 'ДОСТИЖЕНИЯ',
  'profile.completed': 'СЦЕНАРИЕВ ЗАКРЫТО',
  'ach.first.title': 'Первая кровь',
  'ach.first.body': 'Закрой первый сценарий — с любым качеством.',
  'ach.clean70.title': 'Холодная голова',
  'ach.clean70.body': 'Качество 70+ в любом сценарии.',
  'ach.hunter.title': 'Охотник',
  'ach.hunter.body': 'Закрой оба архивных сценария.',
  'ach.scholar.title': 'Архивариус',
  'ach.scholar.body': 'Открой три темы Академии.',
  'more.sections': 'ВСЕ РАЗДЕЛЫ',
  'more.about': 'О ТРЕНАЖЁРЕ',
  'more.aboutBody': 'SIGNAL ARENA — тренажёр качества решений на исторических ситуациях. Не биржа, не сигналы, не обещание дохода.',
  'more.legal': 'ПРАВОЕ И ДИСКЛЕЙМЕРЫ',
  'more.legalBody': 'Обучающий тренажёр на исторических данных, а не инвестиционная рекомендация. Внутриигровые ресурсы не выводятся.',
  'scen.mvp-001.context': 'Актив три дня рос на новостях. Толпа празднует пробой. Объём на пробое — мертворождённый.',
  'scen.mvp-001.goal': 'Реши до раскрытия архива: здесь есть сигнал — или только шум с фанфарами?',
  'scen.mvp-001.fact': 'Пробой не удержался: цена вернулась под уровень за 6 часов, объём покупок иссяк.',
  'scen.mvp-001.source': 'Архив · спот · 15m · датасет v0.1.0',
  'scen.mvp-001.d0': 'Войти на пробое',
  'scen.mvp-001.d0r': 'Вход в шум без подтверждения: пробой без объёма — классическая жертва толпе.',
  'scen.mvp-001.d1': 'Ждать ретест',
  'scen.mvp-001.d1r': 'Терпеливое решение: подтверждение ретестом отделяет сигнал от фанфар.',
  'scen.mvp-001.d2': 'Сократить риск',
  'scen.mvp-001.d2r': 'Осторожно, но без позиции сокращать нечего: действие мимо контекста.',
  'scen.mvp-001.d3': 'Остаться вне рынка',
  'scen.mvp-001.d3r': 'Вне рынка — тоже решение: нет подтверждения — нет сделки.',
  'scen.mvp-001.tab.chart': 'Структура: три дня роста, пробой уровня. Объём на пробое ниже среднего.',
  'scen.mvp-001.tab.volume': 'Объём покупок затухает три сессии подряд. Пробой случился на самом тонком баре.',
  'scen.mvp-001.tab.news': 'Заголовки трубят о «новой эре». Новость — не сигнал, а well-timed шум.',
  'scen.mvp-001.tab.social': 'Соцфон: эйфория. Индекс веры в график зашкаливает — толпа уже внутри.',
  'scen.mvp-001.step2q': 'Какой риск допустим, если входишь?',
  'scen.mvp-001.s0': '0.5% — пережить ошибку',
  'scen.mvp-001.s0r': 'Риск, с которым можно жить, даже если рынок идёт не туда.',
  'scen.mvp-001.s1': '2% — стандартная ставка',
  'scen.mvp-001.s1r': 'Терпимо, но для неподтверждённого пробоя — щедрость за счёт депозита.',
  'scen.mvp-001.s2': '10% — пан или пропал',
  'scen.mvp-001.s2r': 'Это не риск-менеджмент, а жертвоприношение с красивым названием.',
  'scen.mvp-002.context': 'Ты в лонге от ретеста. Цена топчется у входа четвёртый час. Стоп близко, эго — ближе.',
  'scen.mvp-002.goal': 'Позиция открыта. Реши: план жив — или ты уже усредняешь надежду?',
  'scen.mvp-002.fact': 'Уровень удержали ещё 2 часа, затем — импульсный слив к стопам. План требовал выхода раньше.',
  'scen.mvp-002.source': 'Архив · perp · 5m · датасет v0.1.0',
  'scen.mvp-002.d0': 'Держать по плану',
  'scen.mvp-002.d0r': 'Дисциплина: условия отмены не сработали — система важнее страха.',
  'scen.mvp-002.d1': 'Сократить половину',
  'scen.mvp-002.d1r': 'Сначала риск: фиксация части снимает давление и сохраняет голову.',
  'scen.mvp-002.d2': 'Усреднить вход',
  'scen.mvp-002.d2r': 'Усреднение ошибки без плана: надежда — самая дорогая валюта.',
  'scen.mvp-002.d3': 'Выйти полностью',
  'scen.mvp-002.d3r': 'Панический выход до отмены идеи: страх тоже умеет маскироваться под риск.',
  'scen.mvp-002.tab.chart': 'Консолидация у точки входа. Структура пока цела, но импульс покупателя угас.',
  'scen.mvp-002.tab.position': 'Позиция: лонг от ретеста, +0.4%. Стоп — за локальным минимумом, риск 1%.',
  'scen.mvp-002.tab.social': 'Толпа требует «держать до луны». Стадо редко платит за твои стопы.',
  'skill.risk-first.title': 'Сначала риск, потом вход',
  'skill.risk-first.body': 'Определи, сколько готов потерять, до того как мечтаешь о прибыли.',
  'skill.no-confirm.title': 'Нет подтверждения — нет сделки',
  'skill.no-confirm.body': 'Пробой без объёма и ретеста — это фанфары, а не сигнал.',
  'skill.htf.title': 'Проверь старший таймфрейм',
  'skill.htf.body': 'Младший ТФ врёт убедительно. Старший — реже и дороже.',
  'skill.news-noise.title': 'Новость — не сигнал',
  'skill.news-noise.body': 'Заголовок продаёт эмоции. Сигнал продаёт только цена с объёмом.',
  'skill.no-average.title': 'Не усредняй ошибку',
  'skill.no-average.body': 'Доливка к убытку без плана превращает ошибку в образ жизни.',
  'skill.flat-ok.title': 'Вне рынка — тоже решение',
  'skill.flat-ok.body': 'Пропуск сделки стоит ноль. Плохая сделка — всегда дороже.',
  'skill.invalidate.title': 'Отмена идеи — заранее',
  'skill.invalidate.body': 'Условие «я был неправ» пишется до входа, а не придумывается в просадке.',
  'skill.plan-profit.title': 'Прибыль не оправдывает нарушение',
  'skill.plan-profit.body': 'Зелёная сделка мимо системы — всё равно красный флаг.',
  'entity.fake-breakout-phantom.body': 'Рисует пробой, заманивает толпу, исчезает до ретеста.',
  'entity.fake-breakout-phantom.tell': 'Пробой уровня на затухающем объёме + эйфория в заголовках.',
  'entity.fake-breakout-phantom.counter': 'Жди ретест. Нет подтверждения — нет сделки.',
  'entity.fomo-wraith.body': 'Шепчет, что поезд уходит. Поезд обычно едет в депо.',
  'entity.fomo-wraith.tell': 'Зуд «войти сейчас», хотя план требовал ждать.',
  'entity.fomo-wraith.counter': 'Пауза 10 минут. Сигнал подождёт, призрак — нет.',
  'entity.leverage-goblin.body': 'Предлагает плечо как shortcut к богатству. Путь ведёт к ликвидации.',
  'entity.leverage-goblin.tell': 'Желание «ускориться» после серии хороших решений.',
  'entity.leverage-goblin.counter': 'Фиксированный риск 0.5–1%. Гоблин голодает на диете.',
  'entity.headline-titan.body': 'Метает заголовки-молнии. Каждая бьёт точно в дисциплину.',
  'entity.headline-titan.tell': 'Решение хочется принять сразу после новости.',
  'entity.headline-titan.counter': 'Новость — в карантин на одну сессию. Сначала график.',
  'entity.anchor-golem.body': 'Приковывает к старой цене. «А ведь было по…» — его заклинание.',
  'entity.anchor-golem.tell': 'Оценка сделки от прошлого экстремума, а не от текущего контекста.',
  'entity.anchor-golem.counter': 'Переоцени позицию от текущей цены, как будто входишь сейчас.',
  'entity.revenge-wraith.body': 'После убытка предлагает отыграться немедленно. Принимает только депозиты.',
  'entity.revenge-wraith.tell': 'Злость после стопа и тяга «вернуть прямо сейчас».',
  'entity.revenge-wraith.counter': 'Протокол «После убытка»: пауза, журнал, разбор. Потом — рынок.',
  'protocol.risk-first.title': 'Сначала риск',
  'protocol.risk-first.rule': 'Оценивается управление риском: размер, стоп, отмена идеи.',
  'protocol.evidence-only.title': 'Только доказательства',
  'protocol.evidence-only.rule': 'Решение должно опираться на факты вкладок, а не на шум.',
  'protocol.noise-quarantine.title': 'Шумовой карантин',
  'protocol.noise-quarantine.rule': 'Новости и соцфон игнорируются: только структура, объём и план.',
  'protocol.flat-ok.title': 'Не входить — тоже решение',
  'protocol.flat-ok.rule': 'Воздержание при слабом сигнале оценивается наравне со сделкой.',
  'protocol.save-system.title': 'Сохранить систему',
  'protocol.save-system.rule': 'Оценивается верность торговому плану: без импровизаций и исключений.',
  'protocol.after-loss.title': 'После убытка',
  'protocol.after-loss.rule': 'Серия после стопа: пауза, снижение риска, запрет на revenge.',
  'protocol.confidence.title': 'Проверка уверенности',
  'protocol.confidence.rule': 'Оценивается калибровка: уверенность должна совпадать с силой доказательств.',
  'arena.mode.title': 'ПРАКТИКА',
  'arena.mode.hero': 'РЫНОК УЖЕ СЛУЧИЛСЯ. ОСТАЛОСЬ ТОЛЬКО ТВОЁ РЕШЕНИЕ.',
  'arena.mode.formats': 'ФОРМАТ',
  'arena.mode.format.free': 'Свободная тренировка',
  'arena.mode.format.freeBody': '1 сценарий · 60–90 сек · подбор по слабым местам',
  'arena.mode.format.series': 'Серия из 3',
  'arena.mode.format.seriesBody': 'Одна тема, растущая сложность · 8–12 мин',
  'arena.mode.format.fix': 'Исправление',
  'arena.mode.format.fixBody': 'Целевая работа по повторяющейся ошибке',
  'arena.mode.choose': 'Выбрать',
  'arena.mode.rule': 'ПРАВИЛО СЕССИИ',
  'arena.mode.ruleHint': 'ВЛИЯЕТ НА ОЦЕНКУ',
  'arena.mode.focus': 'ФОКУС КОНТЕНТА',
  'arena.mode.focus.all': 'ВСЕ',
  'arena.mode.focus.structure': 'СТРУКТУРА',
  'arena.mode.focus.noise': 'ШУМ',
  'arena.mode.focus.risk': 'РИСК',
  'arena.mode.focus.psycho': 'ПСИХО',
  'arena.mode.focus.web3': 'WEB3',
  'arena.mode.start': 'Начать →',
  'arena.mode.hashOk': 'ХЭШ',
  'arena.brief.phase': 'ФАЗА',
  'arena.brief.timeframe': 'ТАЙМФРЕЙМ',
  'arena.brief.rule': 'ПРАВИЛО',
  'arena.brief.difficulty': 'СЛОЖНОСТЬ',
  'arena.brief.preEntry': 'До входа',
  'arena.brief.inPosition': 'Внутри позиции · t₀+3',
  'arena.brief.situation': 'СИТУАЦИЯ · ИСТОРИЧЕСКАЯ',
  'arena.brief.tabs': 'ИСТОЧНИКИ В СЦЕНАРИИ',
  'arena.brief.start': 'К ЗАДАЧЕ →',
  'arena.pressure': 'ДАВЛЕНИЕ',
  'arena.disclaimer': 'НЕ ФИНРЕКОМЕНДАЦИЯ · ИСТОРИЧЕСКИЕ ДАННЫЕ · ИСХОД УЖЕ ЗАФИКСИРОВАН',
  'arena.skillsApplied': 'ПРИМЕНЕНО',
  'arena.of': 'ИЗ',
  'arena.moreSkills': 'ЕЩЁ КАРТЫ — В АКАДЕМИИ',
  'arena.catalog.title': 'ИСТОЧНИКИ СЦЕНАРИЯ',
  'arena.catalog.sub': 'Не все нужны в каждом задании. Монеты открывают доступ к данным, но не к ответу.',
  'arena.catalog.open': 'открыто',
  'arena.catalog.coins': 'монет',
  'arena.catalog.level': 'уровень',
  'arena.catalog.phaseOnly': 'только в фазе «внутри»',
  'arena.catalog.note': 'Оплата даёт только доступ к данным. Правильный ответ, буст оценки и повышенный риск купить нельзя.',
  'arena.skill.type': 'ТИП',
  'arena.skill.mastery': 'МАСТЕРСТВО',
  'arena.skill.used': 'ПРИМЕНЕНА',
  'arena.skill.times': 'РАЗ',
  'arena.skill.avgQuality': 'СРЕДНЕЕ КАЧЕСТВО',
  'arena.skill.studyIn': 'ГДЕ ИЗУЧАЕТСЯ',
  'arena.skill.toAcademy': 'В Академию',
  'arena.skill.apply': 'Применить',
  'arena.skill.kindName.reading': 'ЧТЕНИЕ',
  'arena.skill.kindName.decision': 'РЕШЕНИЕ',
  'arena.skill.kindName.protection': 'ЗАЩИТА',
  'arena.skill.cardOf.reading': 'КАРТА ЧТЕНИЯ',
  'arena.skill.cardOf.decision': 'КАРТА РЕШЕНИЯ',
  'arena.skill.cardOf.protection': 'КАРТА ЗАЩИТЫ',
  'arena.confirm.selected': 'ВЫБРАНО',
  'arena.confirm.changeable': 'можно изменить до фиксации',
  'arena.confirm.change': 'Изменить',
  'arena.confirm.lockNote': 'Фиксация необратима: дальше — раскрытие.',
  'arena.reveal.layerFact': 'СЛОЙ 1 · ФАКТ РЫНКА',
  'arena.reveal.layerConsequence': 'СЛОЙ 2 · ПОСЛЕДСТВИЕ ТВОЕГО ПОВЕДЕНИЯ',
  'arena.reveal.speed': 'СКОРОСТЬ',
  'arena.reveal.replay': '▶ ПОВТОРИТЬ',
  'arena.reveal.frame': 'КАДР',
  'arena.volume.book': 'СТРУКТУРА ЛИКВИДНОСТИ',
  'arena.volume.asks': 'ASKS',
  'arena.volume.bids': 'BIDS',
  'arena.volume.wall': 'КИТОВАЯ СТЕНА',
  'arena.volume.wallBody': 'выше уровня пробоя',
  'arena.volume.spread': 'СПРЕД',
  'arena.volume.breakVol': 'ОБЪЁМ НА ПРОБОЕ',
  'arena.volume.toAvg': 'К СРЕДНЕМУ',
  'verdict.step': 'ШАГ',
  'verdict.nextStep': 'ДАЛЕЕ',
  'verdict.breakdown': 'РАЗБОР: ФАКТ → ЛОГИКА → ПРАВИЛО',
  'verdict.logic': 'ЛОГИКА',
  'verdict.sources': 'ИСТОЧНИКИ И МЕТОДИКА',
  'verdict.dataset': 'ДАТАСЕТ',
  'verdict.content': 'КОНТЕНТ',
  'verdict.method': 'МЕТОДИКА',
  'verdict.methodBody': 'Исторический отрезок зафиксирован заранее: датасет, точка t₀ и продолжение проверяются по хэшу. Оценка — по логике, риску и дисциплине, а не по направлению цены.',
  'verdict.hash': 'ХЭШ БУДУЩЕГО',
  'verdict.dim.context': 'КОНТЕКСТ',
  'verdict.dim.evidence': 'ДОКАЗАТЕЛЬСТВА',
  'verdict.dim.action': 'ДЕЙСТВИЕ',
  'verdict.dim.risk': 'РИСК',
  'verdict.dim.discipline': 'ДИСЦИПЛИНА',
  'scen.mvp-001.tf': '15M',
  'scen.mvp-002.tf': '5M',
  'skill.risk-first.short': 'СНАЧАЛА РИСК',
  'skill.no-confirm.short': 'БЕЗ ОБЪЁМА — НЕТ',
  'skill.htf.short': 'СТАРШИЙ TF',
  'skill.news-noise.short': 'НОВОСТЬ ≠ СИГНАЛ',
  'skill.no-average.short': 'НЕ УСРЕДНЯЙ',
  'skill.flat-ok.short': 'ВНЕ РЫНКА',
  'skill.invalidate.short': 'ОТМЕНА ЗАРАНЕЕ',
  'skill.plan-profit.short': 'ПЛАН > ПРИБЫЛИ',
  'app.brand': 'SIGNAL ARENA',
  'app.updating': 'Обновление датасета',
  'app.datasetLine': 'Датасет {v} · хэш проверен',
  'app.boot.loading': 'Загрузка',
  'app.boot.netErr': 'Ошибка сети',
  'auth.step': 'ШАГ 1 ИЗ 3 · ДОСТУП',
  'auth.title': 'ВХОД БЕСПЛАТНЫЙ',
  'auth.sub': 'Выход обычно дороже. Но здесь он тоже бесплатный.',
  'auth.apple': 'Продолжить с Apple',
  'auth.google': 'Продолжить с Google',
  'auth.or': 'ИЛИ',
  'auth.guest': 'Играть без аккаунта · 3 сценария',
  'auth.consent': 'Продолжая, вы соглашаетесь с тем, что игра — обучающий тренажёр на исторических данных, а не инвестиционная рекомендация.',
  'auth.docs': 'Условия · Конфиденциальность',
  'calib.step': 'ШАГ 2 ИЗ 3 КАЛИБРОВКА',
  'calib.wipeTitle': 'СКОЛЬКО РАЗ ТЕБЯ УЖЕ ЛИКВИДИРОВАЛИ?',
  'calib.wipeSub': 'От ответа не зависит ни оценка, ни доступ. Зависит только длина объяснений.',
  'calib.wipe.0': 'Ни разу. Я тут первый день',
  'calib.wipe.1': 'Пару раз. Запомнилось',
  'calib.wipe.2': 'Регулярно. Ищу систему',
  'calib.wipe.3': 'Торгую профессионально',
  'calib.focusTitle': 'ЧТО ТРЕНИРУЕШЬ В ПЕРВУЮ ОЧЕРЕДЬ',
  'calib.topic.entries': 'Входы',
  'calib.topic.hold': 'Удержание',
  'calib.topic.psycho': 'Психология',
  'calib.topic.news': 'Шум и новости',
  'calib.topic.web3': 'Web3-риски',
  'calib.skip': 'Пропустить',
  'calib.next': 'Дальше',
  'calib.limitToast': 'Лимит {n} достигнут',
  'ob.title': 'ОНБОРДИНГ',
  'ob.hint': 'ПОДСКАЗКА',
  'ob.s1.hint': 'Сначала читаешь ситуацию. Потом всё остальное.',
  'ob.s2.hint': 'График обрезан на t₀. Будущее зафиксировано заранее.',
  'ob.s3.hint': 'Второй источник может спорить с первым.',
  'ob.s4.hint': 'Карта не даёт ответ. Она даёт вопрос.',
  'ob.s5.hint': 'Четыре варианта. Не входить — тоже решение.',
  'ob.s6.hint': 'Убыток может получить 100. Прибыль может получить 20.',
  'ob.s7.hint': 'Дополнительный шаг бывает не всегда. Это норма.',
  'ob.s8.hint': 'Угрозы — давление, а не враги с HP.',
  'ob.s9.hint': 'Правило говорит, за что тебя оценят.',
  'ob.s10.hint': 'Каркас открыт полностью. Дальше будет только тише и сложнее.',
  'ob.skip': 'Пропустить объяснения',
  'ob.toArena': 'В Практику',
  'ob.next': 'Дальше',
  'ob.noScore': 'Без оценки и без штрафов до шага 6',
  'home.hero': 'СЕГОДНЯ РЫНОК СНОВА ПЕРЕСМАТРИВАЕТ РЕАЛЬНОСТЬ.',
  'home.streak': 'Серия {days} · качество решений за неделю {q} / 100',
  'home.scenarioOf': 'СЦЕНАРИЙ {n}/{total}',
  'home.seriesLeft': 'Правило: {rule} · осталось {n} сценария',
  'home.seriesOf': 'Серия из {n} · {topic}',
  'home.more': 'Дальше →',
  'home.modes': 'РЕЖИМЫ',
  'home.mode.arena.sub': 'сценарии и решения',
  'home.mode.academy.sub': 'теория → практика',
  'home.mode.threats.sub': '{n} из {total} угроз',
  'home.mode.journal.sub': '{n} паттерна в работе',
  'home.mode.journal.title': 'ЖУРНАЛ',
  'home.mode.tourn.sub': 'окно закроется {d}',
  'home.mode.market.sub': 'только косметика',
  'home.daily.lesson': 'Урок дня · {title}',
  'home.daily.lessonMeta': '{dur} · +{xp} XP',
  'home.daily.ready': 'ГОТОВ',
  'home.daily.fix': 'Исправление · {code}',
  'home.daily.fixMeta': '{title} · {done}/{total}',
  'home.daily.active': 'АКТИВНА',
  'home.daily.tournMeta': '{done} из {total} сценариев сдано',
  'home.daily.tournTitle': 'Турнир · {name}',
  'home.footnote': 'Не финрекомендация · исторические ситуации · будущее зафиксировано',
  'home.streakRisk': 'Серия сгорит через {h} — добей урок дня.',
  'home.paused': 'Сессия на паузе',
  'home.streakDanger': 'Серия в опасности',
  'home.allDone': 'На сегодня всё. Архив подождёт до завтра.',
  'notif.title': 'УВЕДОМЛЕНИЯ',
  'notif.newCount': '{n} НОВЫХ',
  'notif.tab.all': 'ВСЕ',
  'notif.tab.progress': 'ПРОГРЕСС',
  'notif.tab.tournaments': 'ТУРНИРЫ',
  'notif.tab.system': 'СИСТЕМА',
  'notif.group.new': 'НОВОЕ',
  'notif.group.earlier': 'РАНЬШЕ',
  'notif.evt.chapterDone.title': 'Глава {n} закрыта',
  'notif.evt.chapterDone.body': '+{coins} монет и новая угроза в списке угроз',
  'notif.evt.tournWindow.title': 'Окно турнира закроется',
  'notif.evt.tournWindow.body': '{name} · сдано {done} из {total}',
  'notif.evt.patternRepeat.title': 'Паттерн повторился {n}-й раз',
  'notif.evt.patternRepeat.body': '{code} · {title}',
  'notif.evt.newSkill.title': 'Новая карта навыка',
  'notif.evt.newSkill.body': '«{title}»',
  'notif.evt.dataset.title': 'Датасет обновлён до v{v}',
  'notif.evt.dataset.body': '{n} ситуаций · хеши пересчитаны',
  'notif.evt.weekDone.title': 'Неделя {n} завершена',
  'notif.evt.weekDone.body': 'Место {place} из {total} · качество {q}',
  'notif.empty': 'Пока тихо',
  'notif.emptySub': 'Учебные события появятся здесь: прогресс, окна турниров, разборы.',
  'notif.allRead': 'Всё прочитано',
  'notif.hasNew': 'Есть новые',
  'search.title': 'ПОИСК ПО ВСЕМУ ПРОДУКТУ',
  'search.placeholder': 'Главы, угрозы, карты, правила…',
  'search.tab.all': 'ВСЕ',
  'search.tab.chapters': 'ГЛАВЫ',
  'search.tab.threats': 'УГРОЗЫ',
  'search.tab.cards': 'КАРТЫ',
  'search.tab.journal': 'ЖУРНАЛ',
  'search.lessonOf': 'урок {n} из {total}',
  'search.skillMeta': 'карта навыка · мастерство {n}/3',
  'search.ruleRef': 'Правило · {title}',
  'search.ruleUsed': 'применён в {n} сценариях',
  'search.journalRef': 'Запись журнала · {code}',
  'search.journalMeta': '{n} повторов · исправление',
  'search.hint': 'Введи запрос: тема, угроза, карта или правило.',
  'search.none': 'Ничего не найдено',
  'search.noneSub': 'Попробуй короче: «пробой», «объём», «стоп».',
  'search.hidden': 'Скрыто античитом',
  'search.fair': 'Идентификаторы активного сценария в поиске скрыты до завершения — античит §15.',
  'search.hasResults': 'Есть результаты',
  'search.threatRow': '{cat} · стадия {n}',
  'search.silhouetteRow': '{cat} · силуэт',
  'ob.zoneEmpty': 'ЗОНА БРАУЗЕРА ЗАРЕЗЕРВИРОВАНА, НО ПУСТА',
  'ob.active': 'Активный шаг',
  'ob.hidden': 'Объяснения скрыты',
  'ob.skipped': 'Шаг пропущен',
  'boot.legal.add': 'Игра не даёт торговых сигналов и не обещает дохода. Внутригровые ресурсы не выводятся.',
  'home.patTitle': 'ПАТТЕРНЫ',
  'calib.focusMax': 'МАКС {n}',
  'arena.mode.emptyTitle': 'Нет новых сценариев',
  'arena.mode.emptyBody': 'Новых ситуаций нет. Повтори старые — качество важнее количества.',
  'arena.mode.st.free': 'Свободная',
  'arena.mode.st.series': 'Серия',
  'arena.brief.of': 'СЦЕНАРИЙ {n}/{total}',
  'arena.brief.hidden': 'СКРЫТО ДО ОТВЕТА',
  'arena.brief.hiddenList': 'Точная дата · инструмент · оригинальные заголовки · уникальные цифры · ссылки на источники',
  'arena.brief.criteria': 'ЧТО ОЦЕНИВАЕТСЯ',
  'arena.brief.tournHidden': 'Турнирный (таймер скрыт)',
  'arena.brief.fixMode': 'С активной fix-миссией',
  'arena.archiveSealed': 'АРХИВ · t₀ ЗАФИКСИРОВАН',
  'arena.decisionsHint': 'ВСЕГДА 4 · ПОСТОЯННОЕ МЕСТО',
  'arena.volume.missing': 'Данные недоступны в архиве',
  'arena.volume.marked': 'Аномалия отмечена игроком',
  'arena.sel.none': 'Ничего не выбрано',
  'arena.sel.card': 'Карта применена',
  'arena.sel.picked': 'Вариант выбран',
  'arena.sel.locked': 'Ответ зафиксирован',
  'arena.liveThreat': 'Активная угроза · уровень {n}',
  'arena.threatTag': 'УГРОЗА',
  'arena.snapshot': 'ВКЛАДКА {tab} · КРАТКИЙ СЛЕПОК',
  'arena.catalog.desc.chart': 'График и структура рынка',
  'arena.catalog.desc.higher-tf': 'Старшие таймфреймы',
  'arena.catalog.desc.volume': 'Объём и ликвидность',
  'arena.catalog.desc.news': 'Новостной фон',
  'arena.catalog.desc.social': 'Социальный сентимент',
  'arena.catalog.desc.macro': 'Макроконтекст',
  'arena.catalog.desc.onchain': 'On-chain и Web3-данные',
  'arena.catalog.desc.position': 'История текущей позиции',
  'arena.catalog.desc.journal': 'Мои правила и журнал',
  'arena.catalog.noCoins': 'Не хватает монет',
  'arena.catalog.locked': 'Откроется на уровне {n}',
  'arena.catalog.allOpen': 'Всё открыто',
  'arena.catalog.somePaid': 'Есть платные',
  'arena.catalog.blocked': 'Заблокировано уровнем',
  'arena.tabsAvail': '{n} ДОСТУПНА',
  'arena.skill.locked': 'Закрыта',
  'arena.skill.lockedCost': '{n} монет',
  'arena.skill.maxed': 'МАСТЕРСТВО МАКС',
  'arena.skill.banned': 'Недоступна в этом правиле',
  'arena.skill.opened': 'Открыта',
  'arena.confirm.lock': 'Зафиксировать решение',
  'arena.confirm.reselect': 'Повторный выбор',
  'arena.confirm.locked': 'Зафиксировано',
  'arena.step2.of': 'ШАГ {n} ИЗ {total}',
  'arena.step2.affects': 'влияет на блок «{dim}»',
  'arena.step2.confirm': 'Подтвердить и раскрыть рынок',
  'arena.step2.blocked': 'Заблокировано правилом',
  'arena.step2.title': 'ДОПОЛНИТЕЛЬНЫЙ ШАГ',
  'arena.step2.none': 'Условия не заданы',
  'arena.intel.source': 'ИСТОЧНИК {letter}',
  'arena.intel.trust': 'Надёжность {n}%',
  'arena.inpos.newsHit': 'НОВОСТЬ ПРИШЛА ПОСЛЕ ВХОДА. КАК ВСЕГДА.',
  'arena.inpos.changed': 'План был. Контекст изменился. План об этом не предупреждали.',
  'arena.intel.evt.news': 'Новость',
  'arena.intel.evt.move': 'Резкое движение',
  'arena.intel.evt.silence': 'Тишина',
  'arena.threatsLive': '{n} угрозы активны',
  'arena.reveal.title': 'РАСКРЫТИЕ',
  'arena.reveal.opened': 'ПРОДОЛЖЕНИЕ РАСКРЫТО',
  'arena.reveal.playing': 'Анимация идёт',
  'arena.reveal.noAnim': 'Анимация отключена в настройках',
  'arena.reveal.toVerdict': 'К оценке качества решения',
  'arena.reveal.factOf': 'ФАКТ {n} ИЗ {total}',
  'arena.reveal.t0': 't₀ · точка решения',
  'arena.reveal.action': 'ДЕЙСТВИЕ',
  'arena.reveal.outcome': 'ИСХОД РЫНКА',
  'arena.reveal.sealed': 'Продолжение было зафиксировано до твоего ответа. Хэш совпадает — данные не подменены.',
  'arena.reveal.paused': 'Пауза',
  'arena.reveal.done': 'Завершено',
  'verdict.rewardLine': '+{xp} XP · +{coins} МОНЕТ · СЕРИЯ {days}',
  'verdict.criteria': 'КРИТЕРИИ',
  'verdict.weights': 'ВЕСА ИЗ БРИФИНГА',
  'verdict.lost': 'ГДЕ ПОТЕРЯНО',
  'verdict.loss.repeat': 'Повтор № {n} · тег {code}',
  'verdict.loss.fix': 'FIX',
  'verdict.logged': 'ЗАПИСАНО В ЖУРНАЛ',
  'verdict.skillUp': 'КАРТА УКРЕПЛЕНА',
  'verdict.quality': 'КАЧЕСТВО РЕШЕНИЯ',
  'verdict.band.highName': 'Высокая оценка',
  'verdict.band.midName': 'Средняя',
  'verdict.band.lowName': 'Низкая',
  'verdict.band.high': 'РЕШЕНИЕ, С КОТОРЫМ МОЖНО ЖИТЬ',
  'verdict.band.highSub': 'Рынок шёл не туда, куда ты думал. Решение от этого не стало хуже.',
  'verdict.dimName.context': 'Учёт контекста',
  'verdict.dimName.evidence': 'Работа с доказательствами',
  'verdict.dimName.action': 'Выбор действия',
  'verdict.dimName.risk': 'Управление риском',
  'verdict.dimName.discipline': 'Дисциплина',
  'verdict.carryRule': 'ПЕРЕНОСИМОЕ ПРАВИЛО',
  'verdict.act.review': 'Разбор',
  'verdict.act.sources': 'Источники',
  'verdict.act.journal': 'В журнал',
  'verdict.act.next': 'Следующее',
  'verdict.edge.loss100': 'Убыток при оценке 100',
  'verdict.edge.win20': 'Прибыль при оценке 20',
  'verdict.alt': 'ЧТО БЫЛО БЫ',
  'verdict.altRow': '{text} · качество {q}',
  'verdict.alt.yours': 'Ваш выбор',
  'verdict.alt.best': 'Идеальный путь',
  'verdict.alt.worst': 'Сценарий разрушения',
  'verdict.threats': 'УГРОЗЫ В ЭТОЙ СИТУАЦИИ',
  'verdict.depth.full': 'Разбор полный',
  'verdict.depth.short': 'Сжатый (высокий уровень)',
  'verdict.depth.deep': 'Расширенный (повторная ошибка)',
  'verdict.opened': 'РАСКРЫТО',
  'verdict.nowTitle': 'ТЕПЕРЬ МОЖНО',
  'verdict.nowBody': 'Сценарий завершён. Идентификаторы больше не скрыты.',
  'verdict.inst': 'ИНСТРУМЕНТ',
  'verdict.tf': 'ТАЙМФРЕЙМ',
  'verdict.period': 'ПЕРИОД',
  'verdict.t0point': 'ТОЧКА t₀',
  'verdict.integrity': 'ДАННЫЕ И ЦЕЛОСТНОСТЬ',
  'verdict.dataSource': 'Источник данных',
  'verdict.dataSourceVal': 'Агрегатор OHLCV · архивный снимок',
  'verdict.rulesTitle': 'Правила оценки',
  'verdict.rulesVal': 'версия {v} · открыты',
  'verdict.press': 'НОВОСТНЫЕ ИСТОЧНИКИ',
  'verdict.linksOn': 'ССЫЛКИ АКТИВНЫ',
  'verdict.tournHold': 'Сценарий в турнире (раскрытие после закрытия окна)',
  'verdict.closedState': 'Закрыто (до ответа)',
  'legal.edu': 'Материал предоставлен в образовательных целях. Исторические результаты не гарантируют будущих.',
  'arena.pauseTitle': 'Пауза',
  'arena.pauseSub': 'РЫНОК ПОДОЖДЁТ. ОН УЖЕ ЗАКРЫЛСЯ В 2021 ГОДУ.',
  'arena.resume': 'Продолжить',
  'arena.pauseRules': 'Правила оценки',
  'arena.pauseA11y': 'Настройки доступности',
  'arena.exitTitle': 'Выйти из сценария?',
  'arena.exitBody': 'Выход без фиксации не штрафуется. При возврате будет тот же сценарий и та же версия данных.',
  'arena.exitYes': 'Сохранить и выйти',
  'arena.exitNo': 'Остаться',
  'arena.autopause': 'Автопауза при потере фокуса',
  'scen.mvp-001.carryRule': 'Нет подтверждения — нет сделки. Правило работает на любом активе и любом таймфрейме.',
  'arena.mode.dataset': 'Датасет v{v} · {n} ситуаций · будущее зафиксировано',
  'arena.catalog.maxTabs': 'Максимум {n} вкладок.',
  'arena.skill.timesMany': '{n} раза',
  'verdict.factIs': 'Факт:',
  'verdict.logicIs': 'Логика:',
  'verdict.act.proceed': 'Продолжить',
  'verdict.sourcesTitle': 'ИСТОЧНИКИ',
  'verdict.dataVer': 'Версия датасета',
  'verdict.dataVerVal': 'v{v} · {n} ситуаций',
  'verdict.hashOf': 'Хэш скрытого продолжения',
  'verdict.hashVal': '{hash} · проверен',
  'verdict.contentVer': 'Версия контента',
  'scen.mvp-001.revealTitle': 'ЦЕНА ВЕРНУЛАСЬ В ДИАПАЗОН ЗА 7 СВЕЧЕЙ.',
  'scen.mvp-001.revealBody': 'Рынок не был против тебя. Ему просто нужна была ликвидность.',
  'scen.mvp-001.outcome': 'Ложный пробой',
  'scen.mvp-001.d1c': 'Ты ждал ретест и не вошёл: условие подтверждения так и не появилось. Позиции нет, ошибки тоже.',
  'scen.mvp-001.logic': 'Движение без участия объёма не имеет того, кто будет его продолжать. Такой пробой чаще собирает стопы, а не начинает тренд.',
  'scen.mvp-001.alt.2': 'Проверить старший TF',
  'scen.mvp-001.alt.3': 'Усреднить с плечом',
  'scen.mvp-001.press.0.name': 'Заявление регулятора',
  'scen.mvp-001.press.0.meta': 'официальный релиз · надёжность 95%',
  'scen.mvp-001.press.1.name': 'Агентство',
  'scen.mvp-001.press.1.meta': 'новостная лента · 80%',
  'scen.mvp-001.press.2.name': 'Анонимный канал',
  'scen.mvp-001.press.2.meta': 'соцсети · 25%',
  'scen.mvp-002.midnews.0': 'Регулятор выразил обеспокоенность',
  'scen.mvp-002.midnews.1': 'Крупный адрес переместил средства',
  'scen.mvp-002.midnews.2': 'Анонимный канал обещает разворот',
  'arena.pause.a11y': 'Настройки доступности',
  'arena.alterTitle': 'АЛЬТЕРНАТИВНЫЕ ВЕТКИ',
  'arena.tab.fact': 'ФАКТ',
  'arena.verdict.ruleDesc': 'Если подтверждение объёмом не появилось до закрытия свечи — идея отменяется без обсуждения.',
  'arena.verdict.lossEx': 'Убыток при оценке {n}',
  'arena.verdict.profitEx': 'Прибыль при оценке {n}',
  'academy.current': 'ТЕКУЩАЯ ГЛАВА',
  'academy.continueLesson': 'Продолжить урок {n} из {total}',
  'academy.map': 'КАРТА ГЛАВ',
  'academy.chaptersOf': '{n} ГЛАВ',
  'academy.retired': 'закрыта · вышла из ротации',
  'academy.lessonsOf': '{done} из {total} уроков',
  'academy.unlocksAfter': 'откроется после главы {n}',
  'academy.ongoing': 'ИДЁТ',
  'academy.daily': 'УРОК ДНЯ',
  'academy.dailyMeta': '{dur} · серия {days}',
  'academy.begin': 'НАЧАТЬ',
  'academy.filterTitle': 'ПОИСК ПО ТЕМАМ',
  'academy.notDone': 'НЕ ПРОЙДЕНО',
  'academy.tree.rule': 'Глава закроется, когда все {n} тем проверены на практике. После этого темы выходят из ротации.',
  'academy.tree.card': 'карта',
  'academy.tree.rewardTitle': 'ОТКРОЕТСЯ ПОСЛЕ ЗАКРЫТИЯ ГЛАВЫ',
  'academy.tree.reward': '+{coins} МОНЕТ · УГРОЗА: {name}',
  'academy.tree.toCheck': 'Проверка мастерства',
  'academy.tree.nextTopic': 'Следующая тема',
  'academy.tree.ready': 'Готова к проверке',
  'academy.lesson.of': 'УРОК {n} ИЗ {total}',
  'academy.lesson.dur': '~{sec} СЕК',
  'academy.lesson.thesis': 'ТЕЗИС',
  'academy.lesson.true': 'Что верно',
  'academy.lesson.false': 'Что ложно',
  'academy.lesson.linked': 'СВЯЗАННАЯ КАРТА',
  'academy.lesson.mastery': 'Мастерство {n}/3',
  'academy.lesson.repeat': 'Повторить',
  'academy.lesson.toPractice': 'К практике →',
  'academy.practice.title': 'ПРАКТИКА УРОКА',
  'academy.practice.noScore': 'БЕЗ ОЦЕНКИ',
  'academy.practice.rule': 'Один вопрос, четыре варианта. Формат такой же, как в Практике.',
  'academy.practice.onlyNew': 'ТОЛЬКО ИЗУЧАЕМАЯ',
  'academy.practice.emptySlot': 'слот пуст',
  'academy.practice.right': 'Верно',
  'academy.practice.wrong': 'Неверно',
  'academy.practice.up': 'Мастерство повышено',
  'academy.check.title': 'ПРОВЕРКА МАСТЕРСТВА',
  'academy.check.ready': 'ГОТОВНОСТЬ К ПРОВЕРКЕ',
  'academy.check.need': 'Нужно {n}% по каждому критерию',
  'academy.check.reqs': 'ТРЕБОВАНИЯ',
  'academy.check.rTopics': 'Все {n} тем главы пройдены',
  'academy.check.rQuality': '{n} сценария с качеством ≥ {q}',
  'academy.check.rClean': 'Ошибка {code} не повторялась {n} сценариев',
  'academy.check.rCard': 'Карта «{title}»: мастерство {n}/3',
  'academy.check.format': 'ФОРМАТ ПРОВЕРКИ',
  'academy.check.formatBody': '3 сценария подряд с гидрой ликвидности. Правило задано системой, подсказок нет, вкладок 5.',
  'academy.check.rows.scenarios': 'СЦЕНАРИЕВ',
  'academy.check.rows.threshold': 'ПОРОГ',
  'academy.check.rows.thresholdVal': '{n} по всем',
  'academy.check.rows.tries': 'ПОПЫТКИ',
  'academy.check.rows.triesVal': 'без лимита',
  'academy.check.rows.cost': 'СТОИМОСТЬ',
  'academy.check.rows.costVal': 'бесплатно',
  'academy.check.fair': 'Проверку нельзя купить, ускорить или пропустить за монеты.',
  'academy.check.train': 'Тренироваться',
  'academy.check.start': 'Начать проверку',
  'academy.check.failed': 'Провалена. Штрафа нет — тренируйся и возвращайся.',
  'academy.check.passed': 'Глава закрыта',
  'academy.chapterOf': 'Глава {n} · {title}',
  'academy.doneTail': 'пройдено',
  'academy.chapterShort': 'ГЛАВА {n}',
  'academy.lessonsRange': 'уроки {a}–{b}',
  'academy.fair': 'Теория открывает практику, а не наоборот',
  'academy.closedReward': 'Закрытая глава → крупная награда монетами + новая угроза',
  'academy.allDone': 'Всё пройдено',
  'academy.tree.retired': 'Закрытая тема выходит из ротации',
  'academy.ch4.t.0': 'Объём как данные',
  'academy.ch4.t.1': 'Средние и всплески',
  'academy.ch4.t.2': 'Стакан и стены',
  'academy.ch4.t.3': 'ЛИКВИДНОСТЬ',
  'academy.ch4.t.4': 'Пробой без объёма',
  'academy.ch4.t.5': 'НЕТ ПОДТВЕРЖДЕНИЯ',
  'academy.ch4.t.6': 'Охота за стопами',
  'academy.ch4.t.7': 'Слиппаж и исполнение',
  'academy.ch4.t.8': 'ЛИМИТ РИСКА',
  'academy.ch4.t.9': 'Корреляции ликвидности',
  'academy.ch4.t.10': 'ПРОВЕРЬ TF',
  'academy.ch4.l5.thesis': 'ОБЪЁМ НЕ ПОКАЗЫВАЕТ НАПРАВЛЕНИЕ. ОН ПОКАЗЫВАЕТ УЧАСТИЕ.',
  'academy.ch4.l5.caption': 'Сравнение: два пробоя одного уровня, разный объём',
  'academy.ch4.l5.true': 'Всплеск объёма говорит о том, что в движении есть участники.',
  'academy.ch4.l5.false': 'Высокий объём не означает, что движение продолжится.',
  'academy.lesson.st.theory': 'Теория',
  'academy.lesson.st.reread': 'Повторное чтение',
  'academy.ch4.l5p.title': 'ОБЪЁМ КАК ПОДТВЕРЖДЕНИЕ',
  'academy.ch4.l5p.q': 'НАЙДИ МЕСТО, ГДЕ ОБЪЁМ СОЛГАЛ.',
  'academy.ch4.l5p.o.0': 'Свеча 3 · всплеск без продолжения',
  'academy.ch4.l5p.o.1': 'Свеча 7 · рост объёма на теле',
  'academy.ch4.l5p.o.2': 'Свеча 12 · пробой на сухом объёме',
  'academy.ch4.l5p.o.3': 'Объём не солгал нигде',
  'academy.practice.st.question': 'Вопрос',
  'academy.check.notReady': 'Не готов',
  'academy.check.running': 'Проверка идёт',
  'academy.chapterHead': 'ГЛАВА {n} {title}',
  'bestiary.of': '{n} ИЗ {total}',
  'bestiary.revealed': 'РАСКРЫТО',
  'bestiary.activeNow': '{n} АКТИВНЫ',
  'bestiary.filter.all': 'ВСЕ',
  'bestiary.cat.market-structure': 'СИГНАЛЫ',
  'bestiary.cat.emotions-behaviour': 'ЭМОЦИИ',
  'bestiary.cat.narratives-info': 'НАРРАТИВЫ',
  'bestiary.cat.risk-exposure': 'РИСК',
  'bestiary.cat.web3-infra': 'WEB3',
  'bestiary.catGroup.market-structure': 'СИГНАЛЫ И СТРУКТУРА',
  'bestiary.catGroup.emotions-behaviour': 'ЭМОЦИИ И ПОВЕДЕНИЕ',
  'bestiary.catGroup.narratives-info': 'НАРРАТИВЫ И ШУМ',
  'bestiary.catGroup.risk-exposure': 'РИСК И ПЛЕЧО',
  'bestiary.catGroup.web3-infra': 'WEB3-ЛОВУШКИ',
  'bestiary.catOf': '{n} ИЗ {total}',
  'bestiary.stage.silhouette': 'СИЛУЭТ',
  'bestiary.stageLabel': 'стадия',
  'bestiary.closed': 'ЗАКРЫТО',
  'bestiary.meetIn': 'встреть в сценарии',
  'bestiary.footnote': 'Угрозы — язык описания давлений и ловушек. У них нет HP и боёв, их нельзя убить.',
  'bestiary.empty': 'Ты пока никого не встретил. Угрозы проявятся в первых сценариях.',
  'bestiary.allOpen': 'Все угрозы раскрыты. Архив признал тебя своим.',
  'bestiary.stageOf': 'СТАДИЯ {n}',
  'bestiary.stat.pressure': 'ДАВЛЕНИЕ',
  'bestiary.stat.meetings': 'ВСТРЕЧ',
  'bestiary.stat.avgq': 'СР. КАЧЕСТВО',
  'bestiary.stat.cat': 'КАТЕГОРИЯ',
  'bestiary.signs': 'ПРИЗНАКИ ПОЯВЛЕНИЯ',
  'bestiary.counters': 'КАРТЫ-КОНТРМЕРЫ',
  'bestiary.seenIn': 'ГДЕ ВСТРЕЧАЛСЯ',
  'bestiary.seenRow': 'Сценарий {n} · качество {q}',
  'bestiary.open': 'ОТКРЫТЬ',
  'bestiary.liveNow': 'Активна сейчас',
  'bestiary.unknown': 'НЕИЗВЕСТНАЯ УГРОЗА',
  'bestiary.nameHidden': 'ИМЯ СКРЫТО',
  'bestiary.nameHiddenSub': 'Ты ещё не сталкивался с этим достаточно больно, чтобы запомнить.',
  'bestiary.stageProgress': '{cur} / {max}',
  'bestiary.howTo': 'КАК ОТКРЫТЬ',
  'bestiary.unlock.chapter': 'Закрыть главу {n} Обучения',
  'bestiary.unlock.progress': 'прогресс {done}/{total}',
  'bestiary.unlock.meet': 'Встретить в сценарии уровня {n}+',
  'bestiary.unlock.current': 'текущий {n}',
  'bestiary.unlock.noBuy': 'Не покупается за монеты',
  'bestiary.unlock.byDesign': 'по дизайну',
  'bestiary.footnoteLow': 'На низкой готовности угрозы не называются прямо: сначала опыт, потом имя.',
  'bestiary.toChapter': 'К главе {n} Обучения',
  'bestiary.condDone': 'Условие выполнено',
  'bestiary.opening': 'Открывается',
  'collection.title': 'КОЛЛЕКЦИЯ',
  'collection.filter.all': 'ВСЕ',
  'collection.filter.reading': 'ЧТЕНИЕ',
  'collection.filter.decision': 'РЕШЕНИЕ',
  'collection.filter.protection': 'ЗАЩИТА',
  'collection.filter.locked': 'ЗАКРЫТЫЕ',
  'collection.opened': 'ОТКРЫТЫ',
  'collection.of': '{n} ИЗ {total}',
  'collection.lockedTitle': 'ЗАКРЫТЫ',
  'collection.unlockLevel': 'уровень {n}',
  'collection.unlocksAt': 'откроется на',
  'collection.footnote': 'Карты не дают преимущества в оценке и не покупаются. Они — язык твоих принципов.',
  'collection.empty': 'Карт пока нет. Первая откроется в онбординге.',
  'collection.mastery': 'МАСТЕРСТВО {n}/3',
  'collection.uses': 'ПРИМЕНЕНИЙ',
  'collection.avgq': 'СР. КАЧЕСТВО',
  'collection.when': 'КОГДА ПРИМЕНЯТЬ',
  'collection.masteryPath': 'ПРОГРЕСС МАСТЕРСТВА',
  'collection.m1': 'Уровень 1 · применить {n} раза',
  'collection.m2': 'Уровень 2 · качество ≥ {q} в {n} сценариях',
  'collection.m3': 'Уровень 3 · применить против {n} разных угроз',
  'collection.mProgress': '{done} из {total} угроз: {names}',
  'collection.linked': 'СВЯЗАННОЕ',
  'collection.toTheory': 'В теорию',
  'collection.train': 'Тренировать',
  'collection.lockedState': 'Закрытая карта',
  'collection.ruleTitle': 'ПРАВИЛО',
  'collection.ruleSub': 'Правило не даёт бонусов. Оно меняет веса критериев и делает дисциплину измеримой.',
  'collection.weight.risk-first': 'Риск 30 · действие 15',
  'collection.weight.evidence-only': 'Доказательства 30',
  'collection.weight.noise-quarantine': 'Соцфон не учитывается',
  'collection.weight.flat-ok': 'Отказ оценивается наравне',
  'collection.weight.save-system': 'Дисциплина 25',
  'collection.weight.after-loss': 'Контекст и риск выше',
  'collection.weight.confidence': 'Нужно обоснование выбора',
  'collection.ruleActive': 'АКТИВЕН',
  'collection.rulePick': 'ВЫБРАТЬ',
  'collection.ruleFoot': 'Правило выбирается до старта сессии и не меняется внутри сценария. В турнире правило одно для всех.',
  'collection.ruleFixed': 'Задан системой',
  'bestiary.footnoteLowShort': 'На низкой готовности угроза не называется прямо',
  'bestiary.partial': 'Частично раскрыто',
  'bestiary.openedIs': 'Раскрыта {n}',
  'entity.fake-breakout-phantom.sign.0': 'Цена вышла за уровень без роста объёма',
  'entity.fake-breakout-phantom.sign.1': 'Старший таймфрейм остаётся в диапазоне',
  'entity.fake-breakout-phantom.sign.2': 'Социальный фон резко единодушен',
  'bestiary.unlockNote': 'Угрозы открываются опытом и закрытыми главами',
  'collection.view.list': 'Список',
  'collection.view.typeFilter': 'Фильтр по типу',
  'skill.no-confirm.when.0': 'Сигнал есть, но второго подтверждения нет',
  'skill.no-confirm.when.1': 'Старший таймфрейм противоречит идее',
  'skill.no-confirm.when.2': 'Социальный фон заменяет данные',
  'collection.linkRule': 'ПРАВИЛО: {title}',
  'collection.ruleOn': 'Выбран',
  'collection.ruleOff': 'Не выбран',
  'journal.hero': 'ТЫ НЕ СЛУЧАЙНЫЙ. ТЫ ПОСЛЕДОВАТЕЛЬНЫЙ.',
  'journal.heroSub': 'За {n} решений система нашла {m} устойчивых паттерна.',
  'journal.sev.crit': 'КРИТИЧНЫЕ',
  'journal.sev.major': 'ЗНАЧИМЫЕ',
  'journal.sev.minor': 'МЕЛКИЕ',
  'journal.sev.fixed': 'ИСПРАВЛЕННЫЕ',
  'pattern.e-007.title': 'Решение до проверки старшего TF',
  'pattern.e-012.title': 'Вход после одной новости',
  'pattern.e-021.title': 'Смена плана после убытка',
  'pattern.e-004.title': 'Отказ от ожидания без причины',
  'pattern.e-030.title': 'Недоценка слиппажа',
  'journal.patMeta': '{code} · {n}× · последний раз {ago}',
  'journal.patFixed': '{code} · исправлено',
  'journal.patFix': 'FIX {done}/{total}',
  'journal.watching': 'НАБЛЮДЕНИЕ',
  'journal.byDims': 'ДИСЦИПЛИНА ПО КРИТЕРИЯМ',
  'journal.lastN': 'ПОСЛЕДНИЕ {n}',
  'journal.foot': 'Журнал не считает прибыль. Он считает, сколько раз ты нарушил свой же план.',
  'journal.tooFew': 'Нужно хотя бы {n} решений — пока {m}.',
  'journal.allFixed': 'Всё исправлено. Нарушать план стало нечем.',
  'journal.sevOf': '{sev} · {n} ПОВТОРОВ',
  'pattern.e-007.body': 'Ты видишь возможность и боишься её проверить, чтобы она не перестала быть возможностью.',
  'journal.p.repeats': 'ПОВТОРОВ',
  'journal.p.avgq': 'СР. КАЧЕСТВО',
  'journal.p.last': 'ПОСЛЕДНИЙ',
  'journal.p.dim': 'КРИТЕРИЙ',
  'journal.p.cause': 'ПРИЧИНА',
  'pattern.e-007.cause': 'В 4 из 5 случаев решение принято в первые 8 секунд после появления ситуации и при открытой вкладке «Соцфон».',
  'journal.p.linked': 'СВЯЗАННЫЕ УГРОЗЫ И КАРТЫ',
  'journal.fixOf': '{done} ИЗ {total}',
  'pattern.e-007.fix.0': 'Сценарий с правилом «Только доказательства»',
  'pattern.e-007.fix.1': 'Сценарий с конфликтом таймфреймов',
  'pattern.e-007.fix.2': 'Сценарий без вкладки «Соцфон»',
  'journal.p.history': 'История',
  'journal.p.continueFix': 'Продолжить fix-миссию',
  'journal.fixActive': 'Миссия активна',
  'journal.fixDone': 'Миссия завершена',
  'journal.patBack': 'Паттерн вернулся',
  'journal.f.all': 'ВСЕ',
  'journal.f.arena': 'ПРАКТИКА',
  'journal.f.academy': 'ОБУЧЕНИЕ',
  'journal.f.tourn': 'ТУРНИР',
  'journal.sortQ': 'КАЧЕСТВО ↓',
  'journal.row.scen': 'Сценарий {n} · {topic}',
  'journal.row.meta': '{decision} · v{v} · {rule}',
  'journal.row.tourn': 'Турнир · Раунд {n}',
  'journal.row.metaNoRule': '{decision} · v{v}',
  'journal.noRule': 'без правила',
  'journal.row.lesson': 'Обучение · глава {ch} урок {n}',
  'journal.row.right': 'Практика · верно',
  'journal.row.wrong': 'Практика · неверно',
  'journal.immutable': 'История неизменяема. Она хранит версию датасета и правил оценки на момент решения.',
  'journal.export': 'Экспорт истории',
  'tourn.active': 'АКТИВНЫЙ ТУРНИР',
  'tourn.weekTitle': '{name} · НЕДЕЛЯ {n}',
  'tourn.closesIn': 'Закрытие через {t} · {n} сценариев',
  'tourn.inGame': 'ВЫ В ИГРЕ',
  'tourn.doneOf': 'Пройдено {done} из {total}',
  'tourn.continueRound': 'Продолжить раунд {n}',
  'tourn.open': 'ОТКРЫТЫЕ ЗАЯВКИ',
  'tourn.ruleFixed': 'Правило задано · старт через {t}',
  'tourn.scenHidden': '{n} сценариев · таймер скрыт',
  'tourn.needLevel': 'требует уровень {n}+',
  'tourn.free': 'БЕСПЛАТНО',
  'tourn.available': 'ДОСТУПНО',
  'tourn.past': 'ЗАВЕРШЁННЫЕ',
  'tourn.pastRow': 'Место {place} из {total} · качество {q}',
  'tourn.results': 'ИТОГИ',
  'tourn.speedNote': 'Скорость не даёт очков. Она только разводит равные результаты.',
  'tourn.none': 'Нет активных турниров. Открытые заявки — ниже.',
  'tourn.locked': 'Нужен уровень {n}',
  'tourn.brief.sub': 'ОДИН ДАТАСЕТ НА ВСЕХ. ОТГОВОРКИ ЗАКОНЧИЛИСЬ.',
  'tourn.brief.scenarios': 'СЦЕНАРИЕВ',
  'tourn.brief.dataset': 'ДАТАСЕТ',
  'tourn.brief.rule': 'ПРАВИЛО',
  'tourn.brief.timer': 'ТАЙМЕР',
  'tourn.hidden': 'скрыт',
  'tourn.brief.tabs': 'ВКЛАДОК',
  'tourn.tabsOf': '{n} из {total}',
  'tourn.brief.tries': 'ПОПЫТКИ',
  'tourn.fair': 'ЦЕЛОСТНОСТЬ',
  'tourn.fairHash': 'Хэш скрытого будущего',
  'tourn.published': 'ОПУБЛИКОВАН',
  'tourn.hashNote': '{hash} · опубликован до открытия окна',
  'tourn.howWin': 'КАК ОПРЕДЕЛЯЕТСЯ МЕСТО',
  'tourn.win1': 'Качество решений',
  'tourn.win1sub': 'сумма 0–100 по {n} сценариям',
  'tourn.win2': 'Соблюдение правила',
  'tourn.win2sub': 'штраф за нарушение',
  'tourn.win3': 'Работа с доказательствами',
  'tourn.win3sub': 'какие вкладки были открыты',
  'tourn.win4': 'Скорость',
  'tourn.win4sub': 'только при полном равенстве',
  'tourn.startRound': 'Начать раунд {n}',
  'tourn.before': 'До старта',
  'tourn.live': 'В процессе',
  'tourn.closed': 'Окно закрыто',
  'tourn.boardOf': '{n} УЧАСТНИКОВ',
  'tourn.tab.all': 'ОБЩИЙ',
  'tourn.tab.friends': 'ДРУЗЬЯ',
  'tourn.division': 'ДИВИЗИОН {n}',
  'tourn.rowClean': 'Правило соблюдено · доказательства {n}/{total}',
  'tourn.rowFaster': '· быстрее',
  'tourn.rowViol': 'Правило {n} нарушение · доказательства {m}/{total}',
  'tourn.youAs': 'ВЫ · {id}',
  'tourn.order': 'ПОРЯДОК СРАВНЕНИЯ',
  'tourn.orderVal': '1 КАЧЕСТВО · 2 ПРАВИЛО · 3 ДОКАЗАТЕЛЬСТВА · 4 СКОРОСТЬ',
  'tourn.orderNote': 'Скорость влияет только при полном совпадении трёх предыдущих критериев — пункты 2 и 3 развели места {a} и {b}.',
  'tourn.prizeNote': 'Награды турнира косметические и контентные. Никаких выводимых активов.',
  'tourn.final': 'Итоговый',
  'tourn.prelim': 'Предварительный',
  'tourn.hiddenUntilClose': 'Скрыт до закрытия окна',
  'tourn.myResult': 'МОЙ РЕЗУЛЬТАТ',
  'tourn.myPlace': 'МЕСТО {place} / {total}',
  'tourn.topQ': 'ТОП {n}% ПО КАЧЕСТВУ',
  'tourn.mySub': 'Одно нарушение правила стоило тебе одного места.',
  'tourn.byRound': 'ПО РАУНДАМ',
  'tourn.roundRow': 'Раунд {n} · {topic}',
  'tourn.roundClean': 'правило',
  'tourn.prizes': 'НАГРАДЫ',
  'tourn.prizeLine': '+{xp} XP · +{coins} МОНЕТ · ЗНАК: {name}',
  'tourn.sourcesOpen': 'Источники всех {n} сценариев открыты после закрытия окна турнира.',
  'tourn.reviewRounds': 'Разбор раундов',
  'tourn.done': 'Завершён',
  'tourn.unfinished': 'Незавершён',
  'tourn.dq': 'Дисквалификация',
  'journal.hasPatterns': 'Есть паттерны',
  'journal.view.list': 'Список',
  'journal.view.modeFilter': 'Фильтр по режиму',
  'pattern.e-007.short': 'вход без подтверждения',
  'tourn.dry.title': 'СУХОЙ ОБЪЁМ',
  'tourn.discipline.title': 'ДИСЦИПЛИНА ПОСЛЕ УБЫТКА',
  'tourn.web3.title': 'WEB3-ГИГИЕНА',
  'tourn.leagueLine': 'ЛИГА СЕЗОНА · ДИВИЗИОН {n}',
  'tourn.timerCalm': 'Таймер не создаёт панику: может быть скрыт',
  'tourn.headerTitle': '{name} НЕДЕЛЯ {n}',
  'market.tab.shop': 'МАГАЗИН',
  'market.tab.pass': 'ПАСС',
  'market.tab.pro': 'ПОДПИСКА',
  'market.tab.authors': 'АВТОРЫ',
  'market.tab.wallet': 'КОШЕЛЁК',
  'market.cosmetic': 'КОСМЕТИКА',
  'market.i.frame-dry.title': 'РАМКА КАРТ «СУХОЙ ОБЪЁМ»',
  'market.i.avatar-skeleton.title': 'АВАТАР «СПОКОЙНЫЙ СКЕЛЕТ»',
  'market.i.theme-gazeta.title': 'ТЕМА ИНТЕРФЕЙСА «ГАЗЕТА»',
  'market.i.stamp-clean.title': 'ШТАМП ЖУРНАЛА «НЕ ВИНОВАТ»',
  'market.i.pack-liquidity.title': 'НАБОР СЦЕНАРИЕВ «ЛИКВИДНОСТЬ 2019–21»',
  'market.i.extra-tab.title': 'ДОП. ВКЛАДКА НА СЦЕНАРИЙ',
  'market.i.extra-tab.body': 'разовое открытие данных',
  'market.packOf': '+{n} исторических ситуаций',
  'market.packLock': '{n} ситуаций · требует главу {ch}',
  'market.closed': 'ЗАКРЫТО',
  'market.preview': 'ПРЕВЬЮ',
  'market.contentExt': 'РАСШИРЕНИЯ КОНТЕНТА',
  'market.never': 'ЗАПРЕЩЕНО ПРОДАВАТЬ',
  'market.never.0': 'готовые правильные ответы',
  'market.never.1': 'буст оценки и рейтинга',
  'market.never.2': 'повышенные лимиты риска',
  'market.never.3': 'базовые защитные знания',
  'market.never.4': 'лутбоксы, влияющие на качество',
  'market.never.5': 'сигналы и прогнозы',
  'market.foot': 'Все покупки косметические. Разочарование — бесплатно.',
  'market.pass.title': 'СИГНАЛ-ПАСС',
  'market.pass.season': 'СЕЗОН {n} · «{name}»',
  'market.pass.left': 'До конца сезона {t}',
  'market.pass.of': '{n} / {total}',
  'market.pass.track': 'ТРЕК НАГРАД',
  'market.pass.tracks': 'БЕСПЛАТНО / PRO',
  'market.pass.rw.0': 'Рамка карт',
  'market.pass.rw.1': '80 монет',
  'market.pass.rw.2': 'Аватар',
  'market.pass.rw.3': 'Набор сценариев',
  'market.pass.rw.4': 'Штамп журнала',
  'market.pass.free': 'БЕСПЛ',
  'market.pass.pro': 'PRO',
  'market.pass.price': 'ЦЕНА PRO-ПАССА',
  'market.pass.for': 'ПРОГРЕСС ЗА',
  'market.pass.forWhat': 'качество',
  'market.pass.notOn': 'НЕ ВЛИЯЕТ НА',
  'market.pass.notWhat': 'оценку',
  'market.pass.burn': 'СГОРАЕТ',
  'market.pass.burnNo': 'нет, контент остаётся',
  'market.pass.fair': 'Пасс не ускоряет обучение и не повышает оценку. Он только меняет внешний вид и объём контента.',
  'market.pass.buy': 'Оформить PRO-пасс · {price}',
  'market.pass.stateFree': 'Бесплатный трек',
  'market.pass.statePro': 'PRO активен',
  'market.pass.ended': 'Сезон завершён',
  'market.pro.hero': 'PRO НЕ ДЕЛАЕТ ТЕБЯ УМНЕЕ. ОН ДАЁТ БОЛЬШЕ МАТЕРИАЛА ДЛЯ ОШИБОК.',
  'market.pro.month': 'МЕСЯЦ',
  'market.pro.year': 'ГОД',
  'market.pro.pick': 'Выбрать',
  'market.pro.included': 'ВХОДИТ',
  'market.pro.in.0': 'Без дневного лимита сценариев',
  'market.pro.in.1': 'Расширенная аналитика журнала',
  'market.pro.in.2': 'Доступ к архиву сезонных наборов',
  'market.pro.in.3': 'Косметические рамки и темы',
  'market.pro.never': 'НЕ ВХОДИТ НИКОГДА',
  'market.pro.out.0': 'Правильные ответы и подсказки',
  'market.pro.out.1': 'Повышение оценки или места в турнире',
  'market.pro.out.2': 'Приоритет в лидерборде',
  'market.pro.cancel': 'Отмена в любое время. Купленный контент остаётся доступным.',
  'market.pro.none': 'Нет подписки',
  'market.pro.active': 'Активна',
  'market.pro.until': 'Отменена (доступ до {date})',
  'market.auth.status': 'СТАТУС ФУНКЦИИ',
  'market.auth.mvpNote': 'В MVP раздел виден, но наполняется только редакцией. Открытые загрузки выключены.',
  'market.auth.afterMvp': 'ПОСЛЕ MVP МОДЕРАЦИЯ ОБЯЗАТЕЛЬНА',
  'market.auth.editorial': 'РЕДАКЦИОННЫЕ НАБОРЫ',
  'market.auth.metaOpen': '{n} ситуаций · методика открыта',
  'market.auth.metaSrc': '{n} ситуаций · источники указаны',
  'market.auth.reqs': 'ТРЕБОВАНИЯ К ЛЮБОМУ НАБОРУ',
  'market.auth.req.0': 'Исторические данные с указанием источника и t₀',
  'market.auth.req.1': 'Зафиксированное продолжение и его хэш',
  'market.auth.req.2': 'Правила оценки без авторской импровизации',
  'market.auth.req.3': 'Запрет на сигналы и прогнозы',
  'market.auth.noMarket': 'Открытый маркетплейс исключён из MVP по §17.',
  'market.auth.stub': 'Заглушка MVP',
  'market.auth.live': 'Каталог активен',
  'market.wallet.coins': 'МОНЕТЫ',
  'market.wallet.coinsSub': 'игровая, невыводимая',
  'market.wallet.laterTag': 'вне MVP · только метка',
  'market.wallet.rules': 'ПРАВИЛА ЭКОНОМИКИ',
  'market.wallet.rule.0': 'XP и ранг нельзя передать или продать',
  'market.wallet.rule.1': 'Монеты тратятся только внутри игры',
  'market.wallet.rule.2': 'Внешний токен не входит в MVP',
  'market.wallet.rule.3': 'Моста «прогресс → токен» не существует',
  'market.wallet.history': 'ИСТОРИЯ ОПЕРАЦИЙ',
  'market.op.chapter': 'Закрытие главы {n}',
  'market.op.tourn': 'Турнир {name}',
  'market.op.item': '{title}',
  'market.op.tab': 'Доп. вкладка · сценарий {n}',
  'market.op.streak': 'Серия {days}',
  'market.wallet.notFinance': 'Не финансовый сервис. Внутренние балансы не являются активом и не подлежат обмену.',
  'market.wallet.zero': 'Нулевой баланс',
  'market.wallet.emptyHist': 'История пуста',
  'profile.levelLine': 'Уровень {lvl} · Сценариев {n} · Серия {days}',
  'profile.xpTo': '{cur} / {need} XP до уровня {next}',
  'profile.cap99': 'Уровень 99 не гарантирован никому. Это не цель, а граница.',
  'profile.byDims': 'КАЧЕСТВО ПО КРИТЕРИЯМ',
  'profile.avgOf': 'СРЕДНЕЕ ЗА {n}',
  'profile.c.cards': 'КАРТ ОТКРЫТО',
  'profile.c.threats': 'УГРОЗ',
  'profile.c.chapters': 'ГЛАВ ЗАКРЫТО',
  'profile.c.fixed': 'ИСПРАВЛЕНО ПАТТЕРНОВ',
  'profile.season': 'СЕЗОН И ЛИГА',
  'profile.divOf': 'Дивизион {div} · сезон {s}',
  'profile.divSub': 'Повышение дивизиона зависит от качества решений, а не от частоты игры.',
  'profile.toAch': 'Достижения и знаки',
  'profile.rookie': 'Пока пусто. Первые цифры появятся после трёх сценариев.',
  'profile.achOf': '{n} ИЗ {total}',
  'profile.achGot': 'ПОЛУЧЕННЫЕ',
  'ach.flat10.title': 'ВНЕ РЫНКА',
  'ach.flat10.body': '10 отказов с оценкой 80+',
  'ach.risk20.title': 'СНАЧАЛА РИСК',
  'ach.risk20.body': '20 сценариев без нарушений',
  'ach.honest.title': 'ЧЕСТНЫЙ ЖУРНАЛ',
  'ach.honest.body': 'исправлен 1 паттерн',
  'ach.streak7.title': 'СЕРИЯ 7',
  'ach.streak7.body': '7 дней подряд',
  'ach.chapter3.title': 'ГЛАВА 3',
  'ach.chapter3.body': 'закрыта полностью',
  'ach.top5.title': 'ТОП 5%',
  'ach.top5.body': 'турнир Неделя 37',
  'ach.noRepeat.title': 'БЕЗ ПОВТОРОВ',
  'ach.noRepeat.body': '30 сценариев без E-007',
  'ach.allChapters.title': 'ВСЕ ГЛАВЫ',
  'ach.allChapters.body': '7 из 7',
  'ach.collector.title': 'СОБИРАТЕЛЬ',
  'ach.collector.body': '32 угрозы',
  'profile.badge': 'ЗНАК',
  'profile.achLocked': 'ЗАКРЫТЫЕ',
  'profile.achFair': 'Ни одно достижение не выдаётся за частоту сделок или виртуальную доходность.',
  'profile.achEmpty': 'Пока пусто. Первое достижение — «Первая кровь».',
  'profile.achAll': 'Всё получено. Архив гордится.',
  'more.rulesRow': 'ПРАВИЛА',
  'more.sub.patterns': '{n} паттерна',
  'more.sub.rules': '{n} доступно',
  'more.sub.tournActive': '{n} активный',
  'more.sub.pass': 'пасс {n}/{total}',
  'more.sub.level': 'уровень {n}',
  'more.sub.collection': '{n} / {total}',
  'more.service': 'СЕРВИС',
  'more.sub.settings': 'язык, доступность, данные',
  'more.sub.notif': 'серия, турниры, урок дня',
  'more.scoring': 'Правила оценки',
  'more.sub.scoring': 'открытая методика',
  'more.sub.legal': 'дисклеймеры, оферта',
  'more.support': 'Поддержка и обратная связь',
  'more.sub.support': 'ошибки в сценариях',
  'settings.ver': 'ВЕРСИЯ {v} · {build}',
  'settings.region': 'ЯЗЫК И РЕГИОН',
  'settings.langName.ru': 'Русский',
  'settings.langName.en': 'English',
  'settings.dateFmt': 'Формат дат и времени',
  'settings.dateFmtVal': 'DD.MM · 24ч · UTC+3',
  'settings.units': 'Единицы цен',
  'settings.unitsSrc': 'как в источнике',
  'settings.a11y': 'ДОСТУПНОСТЬ',
  'settings.bigText': 'Увеличенный текст',
  'settings.contrast': 'Высокий контраст',
  'settings.cbPalette': 'Цветослепые палитры графика',
  'settings.noTimers': 'Отключить таймеры в турнирах',
  'settings.data': 'ДАННЫЕ И ПРОЗРАЧНОСТЬ',
  'settings.showDataset': 'Показывать версию датасета на экране задания',
  'settings.showHash': 'Показывать хэш скрытого будущего',
  'settings.export': 'Экспорт журнала решений',
  'settings.exportFmt': 'CSV / JSON',
  'settings.wipe': 'Удалить аккаунт и данные',
  'settings.wipeWarn': 'необратимо',
  'settings.fair': 'Настройки не влияют на сложность и оценку. Отключение таймера разрешено всем.',
  'legal.mustRead': 'ОБЯЗАТЕЛЬНО К ПОКАЗУ',
  'legal.hero': 'ЭТО НЕ ФИНАНСОВАЯ РЕКОМЕНДАЦИЯ.',
  'legal.heroSub': 'Игра учит качеству решений на исторических данных и не даёт сигналов, прогнозов и инвестиционных советов.',
  'legal.notTitle': 'ЧЕМ ПРОДУКТ НЕ ЯВЛЯЕТСЯ',
  'legal.not.0': 'Торговым терминалом и симулятором биржи',
  'legal.not.1': 'Демо-счётом или брокером',
  'legal.not.2': 'Игрой play-to-earn с выводом средств',
  'legal.not.3': 'Сервисом сигналов и прогнозов',
  'legal.not.4': 'Казино или азартной игрой на деньги',
  'legal.docs': 'ДОКУМЕНТЫ',
  'legal.doc.terms': 'Пользовательское соглашение',
  'legal.doc.privacy': 'Политика обработки данных',
  'legal.doc.refunds': 'Правила покупок и возвратов',
  'legal.doc.scoring': 'Методика оценки решений',
  'legal.doc.sources': 'Источники исторических данных',
  'legal.doc.sourcesSub': 'перечень',
  'legal.satire': 'Сатира касается поведения рынка и индустрии, а не конкретных пострадавших людей.',
  'legal.accept': 'Принимаю',
  'legal.firstRun': 'Продолжая, ты принимаешь документы выше.',
  'push.of': '{n} ИЗ {total} ВКЛ',
  'push.types': 'ТИПЫ СОБЫТИЙ',
  'push.evt.lesson': 'Урок дня готов',
  'push.evt.lessonSub': 'ежедневно 10:00',
  'push.evt.streak': 'Серия в опасности',
  'push.evt.streakSub': 'за 3 ч до обнуления',
  'push.evt.tourn': 'Закрытие окна турнира',
  'push.evt.tournSub': 'за 6 ч',
  'push.evt.content': 'Новые сценарии и главы',
  'push.evt.contentSub': 'при выходе',
  'push.evt.support': 'Ответ поддержки',
  'push.evt.supportSub': 'по событию',
  'push.evt.promo': 'Акции магазина',
  'push.evt.promoSub': 'не чаще 1 раза в неделю',
  'push.quiet': 'РЕЖИМ ТИШИНЫ',
  'push.from': 'НАЧАЛО',
  'push.to': 'КОНЕЦ',
  'push.days': 'ДНИ',
  'push.daily': 'ежедневно',
  'push.channel': 'КАНАЛ',
  'push.banned': 'ЗАПРЕЩЁННЫЕ ФОРМАТЫ',
  'push.ban.0': 'Сообщения о «упущенной выгоде»',
  'push.ban.1': 'Ложная срочность и таймеры в пушах',
  'push.ban.2': 'Давление на возврат после проигрыша',
  'push.save': 'Сохранить',
  'push.allOff': 'Всё выключено',
  'push.quietOn': 'Режим тишины активен',
  'market.i.pack-news.title': 'НАБОР СЦЕНАРИЕВ «НОВОСТНЫЕ ШОКИ»',
  'market.i.pack-liquidity.short': 'ЛИКВИДНОСТЬ 2019–21',
  'market.i.pack-news.short': 'НОВОСТНЫЕ ШОКИ',
  'market.neverNote': 'Нельзя продавать ответы, бусты, лимиты риска, сигналы',
  'market.view.catalog': 'Каталог',
  'market.wallet.hasBalance': 'Есть баланс',
  'profile.level.mid': 'Уровень средний',
  'profile.level.high': 'Высокий уровень',
  'profile.achPartial': 'Частично',
  'more.collectionRow': 'КОЛЛЕКЦИЯ КАРТ',
  'more.st.badged': 'С бейджами уведомлений',
  'settings.a11yOn': 'Режим доступности включён',
  'push.st.on': 'Включено',
  'ea.title': 'EARLY ACCESS',
  'ea.alphaHero': 'АЛЬФА. ВСЁ РАБОТАЕТ НЕ ТАК, КАК БУДЕТ.',
  'ea.alphaSub': 'Ранние участники видят статус разработки и помогают выбрать, что делать дальше.',
  'ea.myStatus': 'СТАТУС УЧАСТНИКА',
  'ea.status': 'Статус',
  'ea.status.early': 'EARLY PLAYER',
  'ea.confirmed': 'подтверждён',
  'ea.byAdmin': 'выдан админом',
  'ea.histNum': 'Номер в истории',
  'ea.histNumVal': '#{n}',
  'ea.disclaimer': 'Не инвестиция · 18+ · токена нет · roadmap может меняться',
  'ea.st.none': 'Обычный игрок',
  'ea.nostatus': 'Без статуса',
  'ea.st.founder': 'Founder + Premium',
  'ea.st.error': 'Проверка статуса не ответила',
  'ea.tab.intro': 'INTRO',
  'ea.tab.status': 'STATUS',
  'ea.tab.help': 'HELP',
  'ea.tab.benefits': 'BENEFITS',
  'ea.tab.roadmap': 'ROADMAP',
  'ea.tab.token': 'TOKEN',
  'ea.tab.cta': 'CTA',
  'ea.next': 'Дальше →',
  'ea.intro.hero': 'SIGNAL ARENA · PROOF OF SKILL',
  'ea.intro.sub': 'Ты внутри ранней альфа-версии. Игра уже работает, но часть систем ещё в разработке.',
  'ea.intro.checking': 'ЧТО МЫ ПРОВЕРЯЕМ СЕЙЧАС',
  'ea.intro.check.0': 'Насколько интересен основной игровой цикл',
  'ea.intro.check.1': 'Возвращаются ли игроки',
  'ea.intro.check.2': 'Какие режимы развивать первыми',
  'ea.intro.can': 'ЧТО МОЖНО ДЕЛАТЬ',
  'ea.intro.can.0': 'Играть бесплатно',
  'ea.intro.can.1': 'Приглашать друзей',
  'ea.intro.can.2': 'Делиться проектом',
  'ea.intro.can.3': 'Отправлять обратную связь',
  'ea.intro.note': 'Ранние участники получат особый статус и внутриигровые преимущества согласно правилам программы.',
  'ea.st.working': 'ЧТО УЖЕ РАБОТАЕТ',
  'ea.st.ready': 'ГОТОВНОСТЬ АЛЬФЫ 7 ИЗ 7 БАЗОВЫХ',
  'ea.st.done': 'готово',
  'ea.st.item.proto': 'Игровой прототип',
  'ea.st.item.cycle': 'Базовый игровой цикл',
  'ea.st.item.tutor': 'Обучающие сценарии',
  'ea.st.item.profile': 'Профиль игрока',
  'ea.st.item.results': 'Результаты матчей',
  'ea.st.item.ref': 'Реферальные ссылки',
  'ea.st.item.fb': 'Сбор обратной связи',
  'ea.st.wip': 'В РАЗРАБОТКЕ',
  'ea.st.wip.0': 'Серверные награды за рефералов',
  'ea.st.wip.1': 'Лидерборды недели и месяца',
  'ea.st.wip.2': 'Автокарточки результата',
  'ea.st.wip.3': 'Расширенная статистика Premium',
  'ea.st.p1': 'P1',
  'ea.st.p2': 'P2',
  'ea.st.note': 'Некоторые функции могут изменяться во время альфа-теста.',
  'ea.help.title': 'КАК ПОМОЧЬ',
  'ea.help.of': 'Выполнено {done} из {total} · награды начисляет сервер',
  'ea.help.step.0': 'Пройди обучение',
  'ea.help.step.1': 'Сыграй несколько матчей',
  'ea.help.step.2': 'Пригласи знакомого',
  'ea.help.step.3': 'Поделись результатом',
  'ea.help.step.4': 'Отправь отзыв или баг-репорт',
  'ea.help.of33': '{n} из {m}',
  'ea.help.todo': 'не сделано',
  'ea.help.done': 'ГОТОВО',
  'ea.help.now': 'СЕЙЧАС',
  'ea.help.wait': 'ЖДЁТ',
  'ea.help.quick': 'БЫСТРЫЕ ДЕЙСТВИЯ',
  'ea.help.note': 'Награды начисляются за реальные действия и могут быть ограничены правилами защиты от накрутки.',
  'ea.ben.title': 'ЧТО ПОЛУЧАЮТ РАННИЕ УЧАСТНИКИ',
  'ea.ben.note': 'Статус выдаётся сервером и отображается в профиле',
  'ea.ben.status': 'Статус раннего игрока',
  'ea.ben.statusSub': 'активен',
  'ea.ben.premium': 'Пожизненный Premium',
  'ea.ben.premiumSub': 'если подтверждён в админ-системе',
  'ea.ben.tests': 'Приоритетный доступ к закрытым тестам',
  'ea.ben.testsSub': 'по очереди',
  'ea.ben.cosmetic': 'Дополнительные косметические награды',
  'ea.ben.cosmeticSub': 'только внешний вид',
  'ea.ben.polls': 'Участие в опросах о развитии',
  'ea.ben.pollsSub': 'ежемесячно',
  'ea.ben.record': 'Запись в истории ранних участников',
  'ea.ben.recordSub': 'номер #0148',
  'ea.ben.not': 'НЕ ВХОДИТ В СТАТУС',
  'ea.ben.notBody': 'Преимущества в оценке, подсказки ответов, доход, доля в проекте.',
  'ea.ben.foot': 'Состав функций может уточняться до публичного релиза.',
  'ea.road.s1': 'ЭТАП 1 · АЛЬФА',
  'ea.road.s1when': 'сейчас',
  'ea.road.s1body': 'Проверка основного игрового цикла и обучение игроков',
  'ea.road.s1kpi': '10K–50K MAU · D30 больше 3%',
  'ea.road.s2': 'ЭТАП 2 · БЕТА',
  'ea.road.s2when': 'месяцы 6–18',
  'ea.road.s2body': 'Профили, лидерборды, реферальная система, аналитика, контент',
  'ea.road.s2kpi': '50K–200K MAU · D30 больше 6%',
  'ea.road.s3': 'ЭТАП 3 · МОНЕТИЗАЦИЯ',
  'ea.road.s3when': 'месяцы 12–24',
  'ea.road.s3body': 'Платные цифровые функции через поддерживаемые Telegram-инструменты',
  'ea.road.s3kpi': '$100K–500K/год · Premium 5–10%',
  'ea.road.s4': 'ЭТАП 4 · WEB3-ИССЛЕДОВАНИЕ',
  'ea.road.s4when': 'месяцы 18–36',
  'ea.road.s4body': 'Изучение NFT, токена и TON только после проверки продукта, экономики, безопасности и юридической модели.',
  'ea.road.s4kpi': '200K–1M MAU · $500K–2M/год',
  'ea.road.s5': 'ЭТАП 5 · МАСШТАБИРОВАНИЕ',
  'ea.road.s5when': 'месяцы 36+',
  'ea.road.s5body': 'Веб-версия, дополнительные платформы, сервисы и партнёрские интеграции',
  'ea.road.s5kpi': '1M–5M MAU · $1M–5M/год',
  'ea.road.foot': 'Roadmap может меняться: отзывы игроков · техническая осуществимость · наличие финансирования · юридические требования.',
  'ea.tok.hero': 'ТОКЕНА НЕТ. И ЭТО НЕ ОПЕЧАТКА.',
  'ea.tok.body1': 'Сейчас у Signal Arena нет запущенного токена, NFT-контракта или кошелька для получения токенов.',
  'ea.tok.body2': 'Блокчейн рассматривается как возможный слой для отдельных цифровых активов и подтверждения владения. Сначала проверяем, нужен ли он игре.',
  'ea.tok.not': 'РАННЕЕ УЧАСТИЕ НЕ ОЗНАЧАЕТ',
  'ea.tok.no.0': 'Гарантированный airdrop',
  'ea.tok.no.1': 'Гарантированную цену',
  'ea.tok.no.2': 'Гарантированный листинг',
  'ea.tok.no.3': 'Обещанную прибыль',
  'ea.tok.no.4': 'Право на долю в проекте',
  'ea.tok.goals': 'РЕАЛИСТИЧНЫЕ ЦЕЛИ',
  'ea.tok.goalsSub': 'по бенчмаркам',
  'ea.tok.y1': 'Год 1',
  'ea.tok.y2': 'Год 2',
  'ea.tok.y3': 'Год 3',
  'ea.tok.survive': '93% GameFi-проектов проваливаются. Наша цель — попасть в топ-10% выживших.',
  'ea.tok.foot': 'Это не инвестиция. Цифровые товары с внутриигровой утилитой могут обесцениться. Только 18+. Проверяйте локальные законы.',
  'ea.cta.hero': 'ГОТОВ ПОМОЧЬ?',
  'ea.cta.sub': 'Пройди первый матч и отправь Signal Arena человеку, которому может быть интересен такой формат.',
  'ea.cta.learn': 'ПРОЙТИ ОБУЧЕНИЕ',
  'ea.cta.share': 'ПОДЕЛИТЬСЯ ИГРОЙ',
  'ea.cta.feedback': 'ОТПРАВИТЬ ОТЗЫВ',
  'ea.cta.channel': 'ПОДПИСАТЬСЯ НА КАНАЛ',
  'ea.cta.where': 'КУДА ВЕДЁТ КАЖДАЯ КНОПКА',
  'ea.cta.row.learn': 'Обучение',
  'ea.cta.row.learnTo': 'закрыть панель → tutorial',
  'ea.cta.row.shareTo': 'панель шеринга',
  'ea.cta.row.fb': 'Отзыв',
  'ea.cta.row.fbTo': 'внешняя форма',
  'ea.cta.row.ch': 'Канал',
  'ea.cta.row.chTo': 'новая вкладка Telegram',
  'ea.cta.foot': 'Панель можно открыть снова в профиле и в разделе «Ещё».',
  'share.open': 'Поделиться',
  'share.title': 'ПОДЕЛИТЬСЯ РЕЗУЛЬТАТОМ',
  'feedback.open': 'Отправить отзыв',
  'feedback.title': 'ОБРАТНАЯ СВЯЗЬ',
  'ea.mainAction': 'ГЛАВНОЕ ДЕЙСТВИЕ',
  'ea.startTrain': 'Начать тренировку',
  'ea.st.firstShow': 'Первый показ',
  'ea.st.manual': 'Открыта вручную',
  'ea.st.alpha': 'Альфа',
  'ea.st.beta': 'Бета',
  'ea.help.allDone': 'Все шаги выполнены',
  'ea.help.manualReview': 'Награда на ручной проверке',
  'ea.road.alpha': 'Альфа активна',
  'ea.road.beta': 'Бета активна',
  'ea.road.moved': 'Этап сдвинут',
  'ea.tok.stAlpha': 'Альфа (токена нет)',
  'ea.tok.stResearch': 'Исследование объявлено',
  'ea.tok.stTerms': 'Условия опубликованы отдельно',
  'ea.cta.stFresh': 'Обучение не пройдено',
  'ea.cta.stDone': 'Обучение пройдено',
  'share.alphaTag': 'АЛЬФА',
  'share.lastMatch': 'ТВОЙ ПОСЛЕДНИЙ МАТЧ',
  'share.mode': 'Режим',
  'share.result': 'Результат',
  'share.yourLink': 'ТВОЯ ССЫЛКА',
  'share.refLink': 'РЕФЕРАЛЬНАЯ ССЫЛКА',
  'share.codeNote': 'КОД 6–8 СИМВОЛОВ СОЗДАЁТСЯ ПРИ ПЕРВОМ ВХОДЕ',
  'share.copyLink': 'СКОПИРОВАТЬ ССЫЛКУ',
  'share.toTelegram': 'ПОДЕЛИТЬСЯ В TELEGRAM',
  'share.makeCard': 'СОЗДАТЬ КАРТОЧКУ',
  'share.fairNote': 'Ссылка одна на все время. Награды начисляются только за реальные действия друга.',
  'share.hasMatch': 'Есть матч',
  'share.noMatch': 'Матчей ещё нет',
  'share.copied': 'Ссылка скопирована',
  'share.offline': 'Оффлайн',
  'share.card.title': 'КАРТОЧКА РЕЗУЛЬТАТА',
  'share.card.size': '{w}×{h}',
  'share.card.headline': 'РЫНОК ПРИНЯЛ МОЁ РЕШЕНИЕ.',
  'share.card.chartNote': 'ГРАФИК СИТУАЦИИ · СТАТИЧНЫЙ SVG',
  'share.card.formats': 'ФОРМАТЫ',
  'share.card.f.post': 'ПОСТ',
  'share.card.f.story': 'СТОРИС',
  'share.card.f.link': 'ЛИНК-ПРЕВЬЮ',
  'share.card.save': 'СОХРАНИТЬ И ОТПРАВИТЬ',
  'share.card.back': 'Назад к шерингу',
  'share.card.techNote': 'Карточка собирается на клиенте из SVG-шаблона: шрифты в кривые, фон растровый WebP до 120 КБ.',
  'share.card.generating': 'Генерация',
  'share.card.ready': 'Готово',
  'share.card.error': 'Ошибка генерации',
  'share.ref.title': 'ПРИГЛАСИ ДРУГА',
  'share.ref.both': 'НАГРАДЫ ОБОИМ',
  'share.ref.hero': 'ПРИГЛАСИ ТОГО, КОМУ ЭТО ДЕЙСТВИТЕЛЬНО ИНТЕРЕСНО.',
  'share.ref.table': 'ТАБЛИЦА НАГРАД',
  'share.ref.evt.tutor': 'Завершил обучение',
  'share.ref.evt.first': 'Первый матч',
  'share.ref.rw.0': '+{xp} XP + косметика',
  'share.ref.evt.back': 'Возврат на следующий день',
  'share.ref.rw.1': '+{xp} XP + бустер',
  'share.ref.you': 'тебе',
  'share.ref.friend': 'другу',
  'share.ref.yours': 'ТВОИ ПРИГЛАШЁННЫЕ',
  'share.ref.total': '{n} всего',
  'share.ref.invited': 'Приглашено',
  'share.ref.active': 'Активных',
  'share.ref.reward': 'Награда',
  'share.ref.friendN': 'Друг {n}',
  'share.ref.st.both': 'обучение и первый матч',
  'share.ref.st.one': 'обучение',
  'share.ref.st.none': 'ещё не начал',
  'share.ref.waiting': 'ждём',
  'share.ref.share': 'Поделиться ссылкой',
  'share.ref.fair': 'Награды начисляются только за реальные действия. Защита от накрутки работает на сервере и игроку не видна.',
  'share.ref.none': 'Нет приглашённых',
  'share.ref.hasActive': 'Есть активные',
  'share.ref.pending': 'Награда на проверке',
  'alpha.envTag': 'DEMO / LOCAL',
  'alpha.xp': 'XP',
  'alpha.level': 'УРОВЕНЬ',
  'alpha.matches': 'МАТЧЕЙ',
  'alpha.wins': 'ПОБЕД',
  'alpha.streak': 'СЕРИЯ',
  'alpha.skill': 'SKILL',
  'alpha.refs': 'РЕФЕРАЛЫ',
  'alpha.more': 'подробнее',
  'alpha.achOf': '{n} из {total}',
  'alpha.token': 'SIGNAL TOKEN',
  'alpha.btn.share': 'SHARE',
  'alpha.btn.settings': 'SETTINGS',
  'alpha.noServer': 'Нет связи с сервером',
  'alpha.premium.title': 'FOUNDER PREMIUM',
  'alpha.premium.status': 'СТАТУС',
  'alpha.premium.lifetime': 'СТАТУС АКТИВЕН ПОЖИЗНЕННО',
  'alpha.premium.body': 'Выдан администрацией как раннему участнику. Включить его из игры нельзя.',
  'alpha.premium.gives': 'ЧТО ДАЁТ',
  'alpha.premium.gives.0': 'Отключение рекламы (в будущей версии)',
  'alpha.premium.gives.1': 'Дополнительные косметические слоты',
  'alpha.premium.gives.2': 'Расширенная статистика',
  'alpha.premium.gives.3': 'Ранний доступ к режимам',
  'alpha.premium.gives.4': 'Повышенный лимит тренировочных попыток',
  'alpha.premium.gives.5': 'Значок Founder',
  'alpha.premium.gives.6': 'Доступ к закрытым событиям',
  'alpha.premium.denies': 'ЧЕГО НЕ ДАЁТ',
  'alpha.premium.denies.0': 'Бесконечный фарм токенов',
  'alpha.premium.denies.1': 'Экономические преимущества',
  'alpha.premium.denies.2': 'Влияние на оценку решений',
  'alpha.premium.foot': 'Статус проверяется при каждом запуске через Telegram. Если проверка не прошла, премиум-блоки просто не показываются.',
  'alpha.premium.on': 'Статус активен',
  'alpha.premium.off': 'Статуса нет',
  'alpha.premium.failed': 'Проверка не прошла',
  'feedback.alphaTag': 'АЛЬФА',
  'feedback.hero': 'СКАЖИ, ГДЕ БОЛЬНО.',
  'feedback.heroSub': 'Один точный отзыв полезнее ста лайков.',
  'feedback.row.form': 'внешняя форма',
  'feedback.row.bug': 'Сообщить об ошибке',
  'feedback.row.bugForm': 'форма баг-репорта',
  'feedback.row.poll': 'Пройти опрос месяца',
  'feedback.row.pollMeta': '5 вопросов · 2 минуты',
  'feedback.row.channel': 'Канал проекта',
  'feedback.row.channelSub': 'новости и отчёты',
  'feedback.row.chat': 'Чат участников',
  'feedback.row.chatSub': 'обсуждение решений',
  'feedback.tips': 'ЧТО ПОЛЕЗНО НАПИСАТЬ',
  'feedback.tipsBody': 'Где было непонятно · на каком экране бросил · что хочется играть дальше · что выглядит нечестно',
  'feedback.extNote': 'Внешние ссылки открываются в новой вкладке. Подписка не требуется для наград.',
  'feedback.sentToday': 'Отзыв уже отправлен сегодня',
  'feedback.pollOff': 'Опрос недоступен',
  'common.on': 'ВКЛ',
  'common.off': 'ВЫКЛ',
  'common.wd.mon': 'Пн',
  'common.wd.tue': 'Вт',
  'common.wd.wed': 'Ср',
  'common.wd.thu': 'Чт',
  'common.wd.fri': 'Пт',
  'common.wd.sat': 'Сб',
  'common.wd.sun': 'Вс',
  'app.chapter': '{n} · {title}',
  'app.chapSub': '{n} · {title} · {sub}',
  'units.time.sec': '{n} сек',
  'units.time.min': '{n} мин',
  'units.time.hour': '{n} ч',
  'units.time.day': '{n} д',
  'units.time.week': '{n} нед',
  'units.time.month': '{n} мес',
  'units.time.ago': '{t} назад',
  'units.xp': '{n} XP',
  'units.coins': '{n} монет',
  'units.pct': '{n}%',
  'backend.err.network': 'Нет соединения с сервером. Проверь интернет.',
  'backend.err.timeout': 'Сервер не ответил вовремя. Попробуй ещё раз.',
  'backend.err.unauth': 'Сессия истекла. Войди снова.',
  'backend.err.forbidden': 'Нет доступа к этому действию.',
  'backend.err.notFound': 'Не найдено: возможно, уже удалено.',
  'backend.err.conflict': 'Данные изменились. Обнови экран.',
  'backend.err.rateLimit': 'Слишком много запросов. Подожди минуту.',
  'backend.err.server': 'Ошибка сервера. Уже чиним.',
  'backend.err.maintenance': 'Технические работы. Вернёмся скоро.',
  'backend.err.badInput': 'Проверь введённые данные.',
  'backend.auth.codeWrong': 'Неверный код. Осталось попыток: {n}.',
  'backend.auth.codeExpired': 'Код истёк. Запроси новый.',
  'backend.auth.codeResent': 'Новый код отправлен.',
  'backend.auth.tooMany': 'Слишком много попыток. Подожди {t}.',
  'backend.save.ok': 'Прогресс сохранён.',
  'backend.save.conflict': 'Прогресс новее на другом устройстве. Выбери, что оставить.',
  'backend.purchase.ok': 'Оплата прошла. Товар твой.',
  'backend.purchase.fail': 'Оплата не прошла. Деньги не списаны.',
  'backend.purchase.owned': 'Уже куплено.',
  'backend.tourn.full': 'Турнир заполнен.',
  'backend.tourn.ended': 'Окно турнира закрыто.',
  'backend.tourn.dup': 'Ты уже участвуешь.',
  'backend.share.linkFail': 'Не удалось создать ссылку.',
  'backend.feedback.ok': 'Спасибо! Отзыв отправлен.',
  'backend.ea.statusFail': 'Не удалось проверить статус участника.',
  'legal.updated': 'Обновлено {date}',
  'pwa.install.title': 'Установи Signal Arena',
  'pwa.install.body': 'Быстрый запуск с домашнего экрана и работа без сети.',
  'pwa.install.cta': 'Установить',
  'pwa.install.later': 'Позже',
  'pwa.update': 'Доступна новая версия. Обновить?',
  'pwa.updateNow': 'Обновить',
  'pwa.offline': 'Нет соединения. Показаны сохранённые данные.',
  'units.time.today': 'сегодня',
  'units.time.yesterday': 'вчера',
  'states.normal': 'Обычный',
  'states.basic': 'Базовое',
};

export const EN: Record<string, string> = {
  'app.tagline': 'DECISION TRAINER · NOT AN EXCHANGE',
  'app.disclaimer': 'The game gives no trading signals and promises no income. In-game resources cannot be withdrawn.',
  'app.loading': 'Loading the archive of market disasters…',
  'nav.home': 'HOME',
  'nav.academy': 'LEARN',
  'nav.arena': 'PRACTICE',
  'nav.bestiary': 'THREATS',
  'nav.more': 'MORE',
  'shell.scenarioProgress': 'SCENARIO',
  'shell.protocol': 'RULE',
  'arena.brief': 'BRIEFING',
  'arena.task': 'TASK',
  'arena.skills': 'SKILL CARDS',
  'arena.decisions': 'DECISION',
  'arena.confirm': 'LOCK DECISION',
  'arena.confirmHint': 'The future is hidden. After the lock — we open the archive.',
  'arena.step2': 'SECOND STEP',
  'arena.futureHidden': 'FUTURE HIDDEN',
  'arena.t0': 't0 · DECISION POINT',
  'arena.unskill': 'REMOVE CARD',
  'arena.pause': 'PAUSE',
  'arena.exit': 'ABANDON SCENARIO',
  'arena.exitHint': 'The market will wait. It is in no hurry at all.',
  'reveal.title': 'ARCHIVE OPENED',
  'reveal.play': 'PLAY CONSEQUENCES',
  'reveal.fact': 'MARKET FACT',
  'reveal.consequence': 'ACTION CONSEQUENCE',
  'reveal.quality': 'DECISION QUALITY',
  'reveal.next': 'NEXT HUNT',
  'reveal.review': 'BREAKDOWN',
  'reveal.rule': 'PORTABLE RULE',
  'verdict.agree': 'THE MARKET AGREED. THAT DOES NOT MEAN YOU WERE RIGHT.',
  'verdict.disagree': 'THE MARKET DISAGREED. THAT DOES NOT MEAN YOU WERE WRONG.',
  'states.loading': 'LOADING DATA',
  'states.loadingSub': 'The market is looking for an excuse. Wait.',
  'states.offline': 'NO CONNECTION',
  'states.offlineSub': 'Good news: the market is not going anywhere either.',
  'states.locked': 'LOCKED',
  'states.lockedSub': 'The entity still finds you an inconvenient victim.',
  'states.error': 'DATA FAILED TO LOAD',
  'states.errorSub': 'Even servers sometimes pretend everything is under control.',
  'states.retry': 'RETRY',
  'states.empty': 'NOTHING HERE YET',
  'states.emptySub': 'Even panic starts with a blank sheet.',
  'states.saved': 'RESULT SAVED',
  'states.savedSub': 'The mistake now officially belongs to history.',
  'states.noTrade': 'FLAT',
  'states.noTradeSub': 'No position opened. No panic either.',
  'academy.title': 'ACADEMY',
  'academy.chapters': 'CHAPTERS',
  'academy.sub': 'Theory explains the principle. Practice checks whether you applied it in noise.',
  'bestiary.title': 'THREATS',
  'bestiary.sub': 'An entity is not an enemy to kill. It is pressure to keep out of the decision.',
  'journal.title': 'DECISION JOURNAL',
  'journal.sub': 'Not a scroll of errors, but history: patterns, strong skills, weak spots.',
  'tournament.title': 'TOURNAMENTS',
  'tournament.sub': 'One dataset for everyone. Win by quality; speed is tie-break only.',
  'market.title': 'MARKET',
  'market.sub': 'Cosmetics and content. Answers, scores and risk limits are not for sale.',
  'profile.title': 'PROFILE',
  'more.title': 'MORE',
  'settings.title': 'SETTINGS',
  'settings.sound': 'SOUND',
  'settings.reduceMotion': 'REDUCE MOTION',
  'settings.language': 'LANGUAGE',
  'home.title': 'HOME',
  'home.continue': 'CONTINUE THE HUNT',
  'home.daily': 'TODAY IN THE ARCHIVE',
  'common.back': 'BACK',
  'common.close': 'CLOSE',
  'common.retry': 'RETRY',
  'home.greet': 'The disaster archive is open. Pick where to be wrong with style today.',
  'home.resume': 'RESUME SCENARIO',
  'home.start': 'START THE HUNT',
  'home.scenarios': 'SCENARIOS',
  'home.sections': 'SECTIONS',
  'home.best': 'BEST',
  'academy.topic': 'TOPIC',
  'academy.train': 'TRAIN IN THE ARENA',
  'academy.linked': 'LINKED SKILLS',
  'bestiary.tell': 'TELL',
  'bestiary.counter': 'COUNTER',
  'bestiary.train': 'HUNT IN THE ARENA',
  'bestiary.mastered': 'MASTERED',
  'bestiary.seen': 'SPOTTED',
  'journal.patterns': 'REPEATING PATTERNS',
  'journal.history': 'DECISION HISTORY',
  'journal.repeat': 'REPLAY RECOMMENDATIONS',
  'journal.best': 'BEST QUALITY',
  'journal.fix': 'FIX',
  'journal.empty': 'Empty so far: clear your first scenario and the journal will collect your patterns.',
  'tourn.join': 'ENTER',
  'tourn.joined': 'YOU ARE IN',
  'tourn.board': 'LEADERBOARD',
  'tourn.you': 'YOU',
  'tourn.note': 'Async: one dataset for everyone, win by quality. Speed is tie-break only.',
  'market.buy': 'BUY',
  'market.owned': 'OWNED',
  'market.balance': 'BALANCE',
  'market.noFunds': 'Not enough credits. The arena pays for quality, not for hope.',
  'market.bought': 'Bought. Cosmetics never affect decision quality — only the style of defeat.',
  'profile.stats': 'STATS',
  'profile.ach': 'ACHIEVEMENTS',
  'profile.completed': 'SCENARIOS CLOSED',
  'more.sections': 'ALL SECTIONS',
  'more.about': 'ABOUT THE TRAINER',
  'more.aboutBody': 'SIGNAL ARENA is a decision-quality trainer on historical situations. Not an exchange, not signals, not an income promise.',
  'more.legal': 'LEGAL & DISCLAIMERS',
  'more.legalBody': 'An educational trainer on historical data, not investment advice. In-game resources cannot be withdrawn.',
  'protocol.risk-first.title': 'Risk first',
  'protocol.risk-first.rule': 'Risk management is scored: size, stop, invalidation.',
  'protocol.evidence-only.title': 'Evidence only',
  'protocol.evidence-only.rule': 'The decision must rest on tab facts, not on noise.',
  'protocol.noise-quarantine.title': 'Noise quarantine',
  'protocol.noise-quarantine.rule': 'News and sentiment ignored: structure, volume and plan only.',
  'protocol.flat-ok.title': 'Flat is a decision',
  'protocol.flat-ok.rule': 'Staying out on a weak signal scores on par with a trade.',
  'protocol.save-system.title': 'Keep the system',
  'protocol.save-system.rule': 'Loyalty to the trading plan is scored: no improvisation, no exceptions.',
  'protocol.after-loss.title': 'After a loss',
  'protocol.after-loss.rule': 'A post-stop series: pause, smaller risk, no revenge.',
  'protocol.confidence.title': 'Confidence check',
  'protocol.confidence.rule': 'Calibration is scored: confidence must match the strength of evidence.',
  'arena.mode.title': 'PRACTICE',
  'arena.mode.hero': 'THE MARKET ALREADY HAPPENED. ONLY YOUR DECISION IS LEFT.',
  'arena.mode.formats': 'FORMAT',
  'arena.mode.format.free': 'Free drill',
  'arena.mode.format.freeBody': '1 scenario · 60–90 sec · matched to weak spots',
  'arena.mode.format.series': 'Series of 3',
  'arena.mode.format.seriesBody': 'One topic, rising difficulty · 8–12 min',
  'arena.mode.format.fix': 'Fix',
  'arena.mode.format.fixBody': 'Targeted work on a repeating mistake',
  'arena.mode.choose': 'Select',
  'arena.mode.rule': 'SESSION RULE',
  'arena.mode.ruleHint': 'AFFECTS SCORING',
  'arena.mode.focus': 'CONTENT FOCUS',
  'arena.mode.focus.all': 'ALL',
  'arena.mode.focus.structure': 'STRUCTURE',
  'arena.mode.focus.noise': 'NOISE',
  'arena.mode.focus.risk': 'RISK',
  'arena.mode.focus.psycho': 'PSYCHO',
  'arena.mode.focus.web3': 'WEB3',
  'arena.mode.start': 'Start →',
  'arena.mode.hashOk': 'HASH',
  'arena.brief.phase': 'PHASE',
  'arena.brief.timeframe': 'TIMEFRAME',
  'arena.brief.rule': 'RULE',
  'arena.brief.difficulty': 'DIFFICULTY',
  'arena.brief.preEntry': 'Pre-entry',
  'arena.brief.inPosition': 'In position · t₀+3',
  'arena.brief.situation': 'SITUATION · HISTORICAL',
  'arena.brief.tabs': 'SOURCES IN SCENARIO',
  'arena.brief.start': 'TO THE TASK →',
  'arena.pressure': 'PRESSURE',
  'arena.disclaimer': 'NOT FINANCIAL ADVICE · HISTORICAL DATA · OUTCOME ALREADY FIXED',
  'arena.skillsApplied': 'APPLIED',
  'arena.of': 'OF',
  'arena.moreSkills': 'MORE CARDS LIVE IN THE ACADEMY',
  'arena.catalog.title': 'SCENARIO SOURCES',
  'arena.catalog.sub': 'Not all are needed in every task. Coins unlock data access, never the answer.',
  'arena.catalog.open': 'open',
  'arena.catalog.coins': 'coins',
  'arena.catalog.level': 'level',
  'arena.catalog.phaseOnly': 'in-position phase only',
  'arena.catalog.note': 'Payment buys data access only. Correct answers, score boosts and extra risk are not for sale.',
  'arena.skill.type': 'TYPE',
  'arena.skill.mastery': 'MASTERY',
  'arena.skill.used': 'APPLIED',
  'arena.skill.times': 'TIMES',
  'arena.skill.avgQuality': 'AVG QUALITY',
  'arena.skill.studyIn': 'STUDIED IN',
  'arena.skill.toAcademy': 'To Academy',
  'arena.skill.apply': 'Apply',
  'arena.skill.kindName.reading': 'READING',
  'arena.skill.kindName.decision': 'DECISION',
  'arena.skill.kindName.protection': 'PROTECTION',
  'arena.skill.cardOf.reading': 'READING CARD',
  'arena.skill.cardOf.decision': 'DECISION CARD',
  'arena.skill.cardOf.protection': 'PROTECTION CARD',
  'arena.confirm.selected': 'SELECTED',
  'arena.confirm.changeable': 'can be changed before the lock',
  'arena.confirm.change': 'Change',
  'arena.confirm.lockNote': 'Locking is final: the reveal comes next.',
  'arena.reveal.layerFact': 'LAYER 1 · MARKET FACT',
  'arena.reveal.layerConsequence': 'LAYER 2 · CONSEQUENCE OF YOUR BEHAVIOUR',
  'arena.reveal.speed': 'SPEED',
  'arena.reveal.replay': '▶ REPLAY',
  'arena.reveal.frame': 'FRAME',
  'arena.volume.book': 'LIQUIDITY STRUCTURE',
  'arena.volume.asks': 'ASKS',
  'arena.volume.bids': 'BIDS',
  'arena.volume.wall': 'WHALE WALL',
  'arena.volume.wallBody': 'above the breakout level',
  'arena.volume.spread': 'SPREAD',
  'arena.volume.breakVol': 'BREAKOUT VOLUME',
  'arena.volume.toAvg': 'VS AVERAGE',
  'verdict.step': 'STEP',
  'verdict.nextStep': 'NEXT',
  'verdict.breakdown': 'BREAKDOWN: FACT → LOGIC → RULE',
  'verdict.logic': 'LOGIC',
  'verdict.sources': 'SOURCES & METHOD',
  'verdict.dataset': 'DATASET',
  'verdict.content': 'CONTENT',
  'verdict.method': 'METHOD',
  'verdict.methodBody': 'The historical slice is fixed in advance: dataset, t₀ and continuation are hash-checked. Scoring rewards logic, risk and discipline — not price direction.',
  'verdict.hash': 'FUTURE HASH',
  'verdict.dim.context': 'CONTEXT',
  'verdict.dim.evidence': 'EVIDENCE',
  'verdict.dim.action': 'ACTION',
  'verdict.dim.risk': 'RISK',
  'verdict.dim.discipline': 'DISCIPLINE',
  'scen.mvp-001.tf': '15M',
  'scen.mvp-002.tf': '5M',
  'skill.risk-first.short': 'RISK FIRST',
  'skill.no-confirm.short': 'NO VOLUME — NO',
  'skill.htf.short': 'HIGHER TF',
  'skill.news-noise.short': 'NEWS ≠ SIGNAL',
  'skill.no-average.short': 'NEVER AVERAGE',
  'skill.flat-ok.short': 'STAY FLAT',
  'skill.invalidate.short': 'INVALIDATE EARLY',
  'skill.plan-profit.short': 'PLAN > PROFIT',
};

/** Ключи без текста (status=todo в keys.tsv): слоты под будущий контент. */
export const COPY_TODO: string[] = [
  'auth.returnTitle',
  'auth.returnSub',
  'auth.upgradeTitle',
  'auth.upgradeBody',
  'auth.upgradeCta',
  'ob.s1.title',
  'ob.s2.title',
  'ob.s3.title',
  'ob.s4.title',
  'ob.s5.title',
  'ob.s6.title',
  'ob.s7.title',
  'ob.s8.title',
  'ob.s9.title',
  'ob.s10.title',
  'home.first.title',
  'home.first.body',
  'verdict.band.mid',
  'verdict.band.midSub',
  'verdict.band.low',
  'verdict.band.lowSub',
  'scen.mvp-001.d0c',
  'scen.mvp-001.d2c',
  'scen.mvp-001.d3c',
  'pattern.e-012.body',
  'pattern.e-021.body',
  'pattern.e-004.body',
  'pattern.e-030.body',
  'pattern.e-012.cause',
  'pattern.e-021.cause',
  'pattern.e-004.cause',
  'pattern.e-030.cause',
  'tourn.dqBody',
  'pattern.e-012.short',
  'pattern.e-021.short',
  'pattern.e-004.short',
  'pattern.e-030.short',
  'tourn.dry.body',
  'tourn.discipline.body',
  'tourn.web3.body',
  'market.i.frame-dry.body',
  'market.i.avatar-skeleton.body',
  'market.i.theme-gazeta.body',
  'market.i.stamp-clean.body',
  'market.i.pack-liquidity.body',
  'legal.doc.termsBody',
  'legal.doc.privacyBody',
  'legal.doc.refundsBody',
  'legal.doc.scoringBody',
  'legal.doc.sourcesBody',
  'push.channelVal',
  'market.i.pack-news.body',
];
