// Copy-keys (минимум для vertical slice; полный i18n — T122).
// Тон: панк-таблоидная криптосатира (style-tone.txt). RU — первый язык MVP.
import type { BrowserTabId } from './schemas.js';

export type Lang = 'ru' | 'en';

export const TAB_LABEL: Record<BrowserTabId, { ru: string; en: string }> = {
  chart: { ru: 'ГРАФИК', en: 'CHART' },
  'higher-tf': { ru: 'СТАРШИЕ ТФ', en: 'HIGHER TF' },
  volume: { ru: 'ОБЪЁМ', en: 'VOLUME' },
  news: { ru: 'НОВОСТИ', en: 'NEWS' },
  social: { ru: 'СОЦФОН', en: 'SENTIMENT' },
  macro: { ru: 'МАКРО', en: 'MACRO' },
  tokenomics: { ru: 'ТОКЕНОМИКА', en: 'TOKENOMICS' },
  onchain: { ru: 'ОНЧЕЙН', en: 'ON-CHAIN' },
  position: { ru: 'ПОЗИЦИЯ', en: 'POSITION' },
  journal: { ru: 'ЖУРНАЛ', en: 'JOURNAL' },
};

const RU: Record<string, string> = {
  'app.tagline': 'ТРЕНАЖЁР РЕШЕНИЙ · НЕ БИРЖА',
  'app.disclaimer':
    'Игра не даёт торговых сигналов и не обещает дохода. Внутриигровые ресурсы не выводятся.',
  'app.loading': 'Загрузка архива рыночных катастроф…',
  'nav.home': 'ГЛАВНАЯ',
  'nav.academy': 'ОБУЧЕНИЕ',
  'nav.arena': 'ПРАКТИКА',
  'nav.bestiary': 'УГРОЗЫ',
  'nav.more': 'ЕЩЁ',
  'shell.scenarioProgress': 'СЦЕНАРИЙ',
  'shell.protocol': 'ПРАВИЛО',
  'arena.brief': 'БРИФИНГ',
  'arena.task': 'ЗАДАЧА',
  'arena.skills': 'КАРТЫ НАВЫКОВ',
  'arena.decisions': 'РЕШЕНИЕ',
  'arena.confirm': 'ЗАФИКСИРОВАТЬ РЕШЕНИЕ',
  'arena.confirmHint': 'Будущее скрыто. После фиксации — раскроем архив.',
  'arena.step2': 'ВТОРОЙ ШАГ',
  'arena.futureHidden': 'БУДУЩЕЕ СКРЫТО',
  'arena.t0': 't0 · ТОЧКА РЕШЕНИЯ',
  'arena.unskill': 'СНЯТЬ КАРТУ',
  'arena.pause': 'ПАУЗА',
  'arena.exit': 'ПОКИНУТЬ СЦЕНАРИЙ',
  'arena.exitHint': 'Рынок подождёт. Он вообще никуда не торопится.',
  'reveal.title': 'АРХИВ РАСКРЫТ',
  'reveal.play': 'ПРОКРУТИТЬ ПОСЛЕДСТВИЯ',
  'reveal.fact': 'РЫНОЧНЫЙ ФАКТ',
  'reveal.consequence': 'ПОСЛЕДСТВИЕ ДЕЙСТВИЯ',
  'reveal.quality': 'КАЧЕСТВО РЕШЕНИЯ',
  'reveal.next': 'СЛЕДУЮЩАЯ ОХОТА',
  'reveal.review': 'РАЗБОР',
  'reveal.rule': 'ПЕРЕНОСИМОЕ ПРАВИЛО',
  'verdict.agree': 'РЫНОК СОГЛАСИЛСЯ. ЭТО НЕ ЗНАЧИТ, ЧТО ТЫ БЫЛ ПРАВ.',
  'verdict.disagree': 'РЫНОК НЕ СОГЛАСИЛСЯ. ЭТО НЕ ЗНАЧИТ, ЧТО ТЫ ОШИБСЯ.',
  'states.loading': 'ЗАГРУЗКА ДАННЫХ',
  'states.loadingSub': 'Рынок ищет оправдание. Подожди.',
  'states.offline': 'СВЯЗИ НЕТ',
  'states.offlineSub': 'Хорошая новость: рынок тоже никуда не убежал.',
  'states.locked': 'ЗАПЕРТО',
  'states.lockedSub': 'Сущность пока считает тебя недостаточно удобной жертвой.',
  'states.error': 'ДАННЫЕ НЕ ЗАГРУЖЕНЫ',
  'states.errorSub': 'Даже сервер иногда делает вид, что всё под контролем.',
  'states.empty': 'ЗДЕСЬ ПОКА ПУСТО',
  'states.emptySub': 'Даже паника начинается с чистого листа.',
  'states.saved': 'РЕЗУЛЬТАТ СОХРАНЁН',
  'states.savedSub': 'Теперь ошибка официально принадлежит истории.',
  'states.noTrade': 'ВНЕ РЫНКА',
  'states.noTradeSub': 'Сделка не открыта. Паника тоже.',
  'academy.title': 'АКАДЕМИЯ',
  'academy.chapters': 'ГЛАВЫ',
  'academy.sub': 'Теория объясняет принцип. Практика проверяет, применил ли ты его в шуме.',
  'bestiary.title': 'УГРОЗЫ',
  'bestiary.sub':
    'Сущность — не враг, которого убивают. Это давление, которое не пускают в решение.',
  'journal.title': 'ЖУРНАЛ РЕШЕНИЙ',
  'journal.sub': 'Не свиток ошибок, а история: паттерны, сильные навыки, слабые зоны.',
  'tournament.title': 'ТУРНИРЫ',
  'tournament.sub': 'Один набор данных на всех. Победа — по качеству, скорость — только tie-break.',
  'market.title': 'МАРКЕТ',
  'market.sub': 'Косметика и контент. Ответы, оценки и риск-лимиты не продаются.',
  'profile.title': 'ПРОФИЛЬ',
  'more.title': 'ЕЩЁ',
  'settings.title': 'НАСТРОЙКИ',
  'settings.sound': 'ЗВУК',
  'settings.reduceMotion': 'МЕНЬШЕ ДВИЖЕНИЯ',
  'settings.language': 'ЯЗЫК',
  'home.title': 'ГЛАВНАЯ',
  'home.continue': 'ПРОДОЛЖИТЬ ОХОТУ',
  'home.daily': 'СЕГОДНЯ В АРХИВЕ',
  'common.back': 'НАЗАД',
  'common.close': 'ЗАКРЫТЬ',
  'common.retry': 'ПОВТОРИТЬ',
  // --- home ---
  'home.greet': 'Архив катастроф открыт. Выбирай, где сегодня ошибаться со вкусом.',
  'home.resume': 'ПРОДОЛЖИТЬ СЦЕНАРИЙ',
  'home.start': 'НАЧАТЬ ОХОТУ',
  'home.scenarios': 'СЦЕНАРИИ',
  'home.sections': 'РАЗДЕЛЫ',
  'home.best': 'ЛУЧШЕЕ',
  // --- academy ---
  'academy.topic': 'ТЕМА',
  'academy.train': 'ТРЕНИРОВАТЬ В АРЕНЕ',
  'academy.linked': 'СВЯЗАННЫЕ НАВЫКИ',
  'academy.ch.risk.title': 'Риск: размер имеет значение',
  'academy.ch.risk.body':
    'Риск определяется до входа: доля депозита, стоп, условие отмены. Рынок платит тем, кто переживает ошибки, а не тем, кто их избегает.',
  'academy.ch.structure.title': 'Структура: читай следы, а не свечи',
  'academy.ch.structure.body':
    'Уровень, пробой, ретест, объём. Отдельная свеча врёт; структура из трёх событий врёт реже. Подтверждение обязательно.',
  'academy.ch.tf.title': 'Таймфреймы: старшие решают',
  'academy.ch.tf.body':
    'Младший таймфрейм показывает шум красиво. Направление и уровни бери со старшего, точку входа — с младшего.',
  'academy.ch.noise.title': 'Шум: карантин для новостей',
  'academy.ch.noise.body':
    'Заголовок — это эмоция с дедлайном. Новость уходит в карантин на сессию; решение — только по структуре и объёму.',
  'academy.ch.discipline.title': 'Дисциплина: система больше сделки',
  'academy.ch.discipline.body':
    'Зелёная сделка мимо плана — красный флаг. Пауза после убытка, журнал, запрет на revenge: скучно, прибыльно, обязательно.',
  'academy.ch.plan.title': 'План: отмена пишется заранее',
  'academy.ch.plan.body':
    'У каждой идеи есть условие «я неправ»: цена, время, событие. Нет условия отмены — нет идеи, есть надежда.',
  // --- bestiary ---
  'bestiary.tell': 'ПРИЗНАК',
  'bestiary.counter': 'КОНТР-ПРИЁМ',
  'bestiary.train': 'ОХОТИТЬСЯ В АРЕНЕ',
  'bestiary.mastered': 'ОСВОЕНА',
  'bestiary.seen': 'ЗАМЕЧЕНА',
  // --- journal ---
  'journal.patterns': 'ПОВТОРЯЮЩИЕСЯ ПАТТЕРНЫ',
  'journal.history': 'ИСТОРИЯ РЕШЕНИЙ',
  'journal.repeat': 'РЕКОМЕНДАЦИИ ПО ПОВТОРУ',
  'journal.best': 'ЛУЧШЕЕ КАЧЕСТВО',
  'journal.fix': 'ИСПРАВЛЕНИЕ',
  'journal.empty':
    'Пока пусто: пройди первый сценарий, и журнал начнёт коллекционировать твои паттерны.',
  // --- tournament ---
  'tourn.join': 'ВОЙТИ',
  'tourn.joined': 'ТЫ ВНУТРИ',
  'tourn.board': 'ЛИДЕРБОРД',
  'tourn.you': 'ТЫ',
  'tourn.note':
    'Асинхронно: один набор данных на всех, победа по качеству. Скорость — только tie-break.',
  'tourn.rookie.title': 'ПЕСОЧНИЦА: ПЕРВАЯ КРОВЬ',
  'tourn.rookie.body': 'Два архивных сценария. Идеально для калибровки прицела.',
  'tourn.risk.title': 'КУБОК ХОЛОДНОЙ ГОЛОВЫ',
  'tourn.risk.body': 'Протокол «Сначала риск». Гоблины плеча не допускаются.',
  // --- market ---
  'market.buy': 'КУПИТЬ',
  'market.owned': 'КУПЛЕНО',
  'market.balance': 'БАЛАНС',
  'market.noFunds': 'Не хватает кредитов. Арена платит за качество, а не за надежду.',
  'market.bought': 'Куплено. Косметика не влияет на качество решений — только на стиль поражения.',
  'market.i.theme-neon.title': 'Тема «Неоновая свалка»',
  'market.i.theme-neon.body': 'Косметическая тема интерфейса. Кислоты станет больше, ошибок — нет.',
  'market.i.avatar-golem.title': 'Аватар «Голем-якорь»',
  'market.i.avatar-golem.body': 'Тяжёлый силуэт для профиля. К старой цене больше не приковывает.',
  'market.i.season1.title': 'Сезонный набор «Паника-99»',
  'market.i.season1.body': 'Рамки и фоны сезона. Паника коллекционная, убытки — нет.',
  // --- profile ---
  'profile.stats': 'СТАТИСТИКА',
  'profile.ach': 'ДОСТИЖЕНИЯ',
  'profile.completed': 'СЦЕНАРИЕВ ЗАКРЫТО',
  'ach.first.title': 'Первая кровь',
  'ach.first.body': 'Закрой первый сценарий — с любым качеством.',
  'ach.clean70.title': 'Холодная голова',
  'ach.clean70.body': 'Качество 70+ в любом сценарии.',
  'ach.hunter.title': 'Охотник',
  'ach.hunter.body': 'Закрой оба архивных сценария.',
  'ach.scholar.title': 'Архивариус',
  'ach.scholar.body': 'Открой три темы Академии.',
  // --- more ---
  'more.sections': 'ВСЕ РАЗДЕЛЫ',
  'more.about': 'О ТРЕНАЖЁРЕ',
  'more.aboutBody':
    'SIGNAL ARENA — тренажёр качества решений на исторических ситуациях. Не биржа, не сигналы, не обещание дохода.',
  'more.legal': 'ПРАВОЕ И ДИСКЛЕЙМЕРЫ',
  'more.legalBody':
    'Обучающий тренажёр на исторических данных, а не инвестиционная рекомендация. Внутриигровые ресурсы не выводятся.',
  // --- fixture: scenario mvp-001 (fake breakout) ---
  'scen.mvp-001.context':
    'Актив три дня рос на новостях. Толпа празднует пробой. Объём на пробое — мертворождённый.',
  'scen.mvp-001.goal': 'Реши до раскрытия архива: здесь есть сигнал — или только шум с фанфарами?',
  'scen.mvp-001.fact':
    'Пробой не удержался: цена вернулась под уровень за 6 часов, объём покупок иссяк.',
  'scen.mvp-001.source': 'Архив · спот · 15m · датасет v0.1.0',
  'scen.mvp-001.d0': 'Войти на пробое',
  'scen.mvp-001.d0r':
    'Вход в шум без подтверждения: пробой без объёма — классическая жертва толпе.',
  'scen.mvp-001.d1': 'Ждать ретест',
  'scen.mvp-001.d1r': 'Терпеливое решение: подтверждение ретестом отделяет сигнал от фанфар.',
  'scen.mvp-001.d2': 'Сократить риск',
  'scen.mvp-001.d2r': 'Осторожно, но без позиции сокращать нечего: действие мимо контекста.',
  'scen.mvp-001.d3': 'Остаться вне рынка',
  'scen.mvp-001.d3r': 'Вне рынка — тоже решение: нет подтверждения — нет сделки.',
  'scen.mvp-001.tab.chart':
    'Структура: три дня роста, пробой уровня. Объём на пробое ниже среднего.',
  'scen.mvp-001.tab.volume':
    'Объём покупок затухает три сессии подряд. Пробой случился на самом тонком баре.',
  'scen.mvp-001.tab.news': 'Заголовки трубят о «новой эре». Новость — не сигнал, а well-timed шум.',
  'scen.mvp-001.tab.social':
    'Соцфон: эйфория. Индекс веры в график зашкаливает — толпа уже внутри.',
  'scen.mvp-001.step2q': 'Какой риск допустим, если входишь?',
  'scen.mvp-001.s0': '0.5% — пережить ошибку',
  'scen.mvp-001.s0r': 'Риск, с которым можно жить, даже если рынок идёт не туда.',
  'scen.mvp-001.s1': '2% — стандартная ставка',
  'scen.mvp-001.s1r': 'Терпимо, но для неподтверждённого пробоя — щедрость за счёт депозита.',
  'scen.mvp-001.s2': '10% — пан или пропал',
  'scen.mvp-001.s2r': 'Это не риск-менеджмент, а жертвоприношение с красивым названием.',
  // --- fixture: scenario mvp-002 (in position) ---
  'scen.mvp-002.context':
    'Ты в лонге от ретеста. Цена топчется у входа четвёртый час. Стоп близко, эго — ближе.',
  'scen.mvp-002.goal': 'Позиция открыта. Реши: план жив — или ты уже усредняешь надежду?',
  'scen.mvp-002.fact':
    'Уровень удержали ещё 2 часа, затем — импульсный слив к стопам. План требовал выхода раньше.',
  'scen.mvp-002.source': 'Архив · perp · 5m · датасет v0.1.0',
  'scen.mvp-002.d0': 'Держать по плану',
  'scen.mvp-002.d0r': 'Дисциплина: условия отмены не сработали — система важнее страха.',
  'scen.mvp-002.d1': 'Сократить половину',
  'scen.mvp-002.d1r': 'Сначала риск: фиксация части снимает давление и сохраняет голову.',
  'scen.mvp-002.d2': 'Усреднить вход',
  'scen.mvp-002.d2r': 'Усреднение ошибки без плана: надежда — самая дорогая валюта.',
  'scen.mvp-002.d3': 'Выйти полностью',
  'scen.mvp-002.d3r': 'Панический выход до отмены идеи: страх тоже умеет маскироваться под риск.',
  'scen.mvp-002.tab.chart':
    'Консолидация у точки входа. Структура пока цела, но импульс покупателя угас.',
  'scen.mvp-002.tab.position':
    'Позиция: лонг от ретеста, +0.4%. Стоп — за локальным минимумом, риск 1%.',
  'scen.mvp-002.tab.social': 'Толпа требует «держать до луны». Стадо редко платит за твои стопы.',
  // --- fixture skills ---
  'skill.risk-first.title': 'Сначала риск, потом вход',
  'skill.risk-first.body': 'Определи, сколько готов потерять, до того как мечтаешь о прибыли.',
  'skill.no-confirm.title': 'Нет подтверждения — нет сделки',
  'skill.no-confirm.body': 'Пробой без объёма и ретеста — это фанфары, а не сигнал.',
  'skill.htf.title': 'Проверь старший таймфрейм',
  'skill.htf.body': 'Младший ТФ врёт убедительно. Старший — реже и дороже.',
  'skill.news-noise.title': 'Новость — не сигнал',
  'skill.news-noise.body': 'Заголовок продаёт эмоции. Сигнал продаёт только цена с объёмом.',
  'skill.no-average.title': 'Не усредняй ошибку',
  'skill.no-average.body': 'Доливка к убытку без плана превращает ошибку в образ жизни.',
  'skill.flat-ok.title': 'Вне рынка — тоже решение',
  'skill.flat-ok.body': 'Пропуск сделки стоит ноль. Плохая сделка — всегда дороже.',
  'skill.invalidate.title': 'Отмена идеи — заранее',
  'skill.invalidate.body':
    'Условие «я был неправ» пишется до входа, а не придумывается в просадке.',
  'skill.plan-profit.title': 'Прибыль не оправдывает нарушение',
  'skill.plan-profit.body': 'Зелёная сделка мимо системы — всё равно красный флаг.',
  // --- fixture entities ---
  'entity.fake-breakout-phantom.body': 'Рисует пробой, заманивает толпу, исчезает до ретеста.',
  'entity.fake-breakout-phantom.tell': 'Пробой уровня на затухающем объёме + эйфория в заголовках.',
  'entity.fake-breakout-phantom.counter': 'Жди ретест. Нет подтверждения — нет сделки.',
  'entity.fomo-wraith.body': 'Шепчет, что поезд уходит. Поезд обычно едет в депо.',
  'entity.fomo-wraith.tell': 'Зуд «войти сейчас», хотя план требовал ждать.',
  'entity.fomo-wraith.counter': 'Пауза 10 минут. Сигнал подождёт, призрак — нет.',
  'entity.leverage-goblin.body':
    'Предлагает плечо как shortcut к богатству. Путь ведёт к ликвидации.',
  'entity.leverage-goblin.tell': 'Желание «ускориться» после серии хороших решений.',
  'entity.leverage-goblin.counter': 'Фиксированный риск 0.5–1%. Гоблин голодает на диете.',
  'entity.headline-titan.body': 'Метает заголовки-молнии. Каждая бьёт точно в дисциплину.',
  'entity.headline-titan.tell': 'Решение хочется принять сразу после новости.',
  'entity.headline-titan.counter': 'Новость — в карантин на одну сессию. Сначала график.',
  'entity.anchor-golem.body': 'Приковывает к старой цене. «А ведь было по…» — его заклинание.',
  'entity.anchor-golem.tell': 'Оценка сделки от прошлого экстремума, а не от текущего контекста.',
  'entity.anchor-golem.counter': 'Переоцени позицию от текущей цены, как будто входишь сейчас.',
  'entity.revenge-wraith.body':
    'После убытка предлагает отыграться немедленно. Принимает только депозиты.',
  'entity.revenge-wraith.tell': 'Злость после стопа и тяга «вернуть прямо сейчас».',
  'entity.revenge-wraith.counter': 'Протокол «После убытка»: пауза, журнал, разбор. Потом — рынок.',
  // --- fixture protocols ---
  'protocol.risk-first.title': 'Сначала риск',
  'protocol.risk-first.rule': 'Оценивается управление риском: размер, стоп, отмена идеи.',
  'protocol.evidence-only.title': 'Только доказательства',
  'protocol.evidence-only.rule': 'Решение должно опираться на факты вкладок, а не на шум.',
  'protocol.noise-quarantine.title': 'Шумовой карантин',
  'protocol.noise-quarantine.rule':
    'Новости и соцфон игнорируются: только структура, объём и план.',
  'protocol.flat-ok.title': 'Не входить — тоже решение',
  'protocol.flat-ok.rule': 'Воздержание при слабом сигнале оценивается наравне со сделкой.',
  'protocol.save-system.title': 'Сохранить систему',
  'protocol.save-system.rule':
    'Оценивается верность торговому плану: без импровизаций и исключений.',
  'protocol.after-loss.title': 'После убытка',
  'protocol.after-loss.rule': 'Серия после стопа: пауза, снижение риска, запрет на revenge.',
  'protocol.confidence.title': 'Проверка уверенности',
  'protocol.confidence.rule':
    'Оценивается калибровка: уверенность должна совпадать с силой доказательств.',
  // --- arena: выбор режима (прототип 4.1) ---
  'arena.mode.title': 'ПРАКТИКА',
  'arena.mode.hero': 'РЫНОК УЖЕ СЛУЧИЛСЯ. ОСТАЛОСЬ ТОЛЬКО ТВОЁ РЕШЕНИЕ.',
  'arena.mode.formats': 'ФОРМАТ',
  'arena.mode.format.free': 'Свободная тренировка',
  'arena.mode.format.freeBody': '1 сценарий · 60–90 сек · подбор по слабым местам',
  'arena.mode.format.series': 'Серия из 3',
  'arena.mode.format.seriesBody': 'Одна тема, растущая сложность · 8–12 мин',
  'arena.mode.format.fix': 'Исправление',
  'arena.mode.format.fixBody': 'Целевая работа по повторяющейся ошибке',
  'arena.mode.choose': 'Выбрать',
  'arena.mode.rule': 'ПРАВИЛО СЕССИИ',
  'arena.mode.ruleHint': 'ВЛИЯЕТ НА ОЦЕНКУ',
  'arena.mode.focus': 'ФОКУС КОНТЕНТА',
  'arena.mode.focus.all': 'ВСЕ',
  'arena.mode.focus.structure': 'СТРУКТУРА',
  'arena.mode.focus.noise': 'ШУМ',
  'arena.mode.focus.risk': 'РИСК',
  'arena.mode.focus.psycho': 'ПСИХО',
  'arena.mode.focus.web3': 'WEB3',
  'arena.mode.start': 'Начать →',
  'arena.mode.hashOk': 'ХЭШ',
  // --- arena: брифинг (прототип 4.2) ---
  'arena.brief.phase': 'ФАЗА',
  'arena.brief.timeframe': 'ТАЙМФРЕЙМ',
  'arena.brief.rule': 'ПРАВИЛО',
  'arena.brief.difficulty': 'СЛОЖНОСТЬ',
  'arena.brief.preEntry': 'До входа',
  'arena.brief.inPosition': 'Внутри позиции · t₀+3',
  'arena.brief.situation': 'СИТУАЦИЯ · ИСТОРИЧЕСКАЯ',
  'arena.brief.tabs': 'ИСТОЧНИКИ В СЦЕНАРИИ',
  'arena.brief.start': 'К ЗАДАЧЕ →',
  // --- arena: каркас задания (прототип 4.3) ---
  'arena.pressure': 'ДАВЛЕНИЕ',
  'arena.disclaimer': 'НЕ ФИНРЕКОМЕНДАЦИЯ · ИСТОРИЧЕСКИЕ ДАННЫЕ · ИСХОД УЖЕ ЗАФИКСИРОВАН',
  'arena.skillsApplied': 'ПРИМЕНЕНО',
  'arena.of': 'ИЗ',
  'arena.moreSkills': 'ЕЩЁ КАРТЫ — В АКАДЕМИИ',
  // --- arena: каталог вкладок (прототип 4.5) ---
  'arena.catalog.title': 'ИСТОЧНИКИ СЦЕНАРИЯ',
  'arena.catalog.sub':
    'Не все нужны в каждом задании. Монеты открывают доступ к данным, но не к ответу.',
  'arena.catalog.open': 'открыто',
  'arena.catalog.coins': 'монет',
  'arena.catalog.level': 'уровень',
  'arena.catalog.phaseOnly': 'только в фазе «внутри»',
  'arena.catalog.note':
    'Оплата даёт только доступ к данным. Правильный ответ, буст оценки и повышенный риск купить нельзя.',
  // --- arena: карта навыка (прототип 4.6) ---
  'arena.skill.type': 'ТИП',
  'arena.skill.mastery': 'МАСТЕРСТВО',
  'arena.skill.used': 'ПРИМЕНЕНА',
  'arena.skill.times': 'РАЗ',
  'arena.skill.avgQuality': 'СРЕДНЕЕ КАЧЕСТВО',
  'arena.skill.studyIn': 'ГДЕ ИЗУЧАЕТСЯ',
  'arena.skill.toAcademy': 'В Академию',
  'arena.skill.apply': 'Применить',
  'arena.skill.kindName.reading': 'ЧТЕНИЕ',
  'arena.skill.kindName.decision': 'РЕШЕНИЕ',
  'arena.skill.kindName.protection': 'ЗАЩИТА',
  'arena.skill.cardOf.reading': 'КАРТА ЧТЕНИЯ',
  'arena.skill.cardOf.decision': 'КАРТА РЕШЕНИЯ',
  'arena.skill.cardOf.protection': 'КАРТА ЗАЩИТЫ',
  // --- arena: подтверждение решения (прототип 4.7) ---
  'arena.confirm.selected': 'ВЫБРАНО',
  'arena.confirm.changeable': 'можно изменить до фиксации',
  'arena.confirm.change': 'Изменить',
  'arena.confirm.lockNote': 'После фиксации продолжение будет раскрыто и изменения невозможны.',
  // --- arena: раскрытие (прототип 4.10) ---
  'arena.reveal.layerFact': 'СЛОЙ 1 · ФАКТ РЫНКА',
  'arena.reveal.layerConsequence': 'СЛОЙ 2 · ПОСЛЕДСТВИЕ ТВОЕГО ПОВЕДЕНИЯ',
  'arena.reveal.speed': 'СКОРОСТЬ',
  'arena.reveal.replay': '▶ ПОВТОРИТЬ',
  'arena.reveal.frame': 'КАДР',
  // --- arena: вкладка объёма (прототип 4.4) ---
  'arena.volume.book': 'СТРУКТУРА ЛИКВИДНОСТИ',
  'arena.volume.asks': 'ASKS',
  'arena.volume.bids': 'BIDS',
  'arena.volume.wall': 'КИТОВАЯ СТЕНА',
  'arena.volume.wallBody': 'выше уровня пробоя',
  'arena.volume.spread': 'СПРЕД',
  'arena.volume.breakVol': 'ОБЪЁМ НА ПРОБОЕ',
  'arena.volume.toAvg': 'К СРЕДНЕМУ',
  // --- verdict: шаги разбора (прототип 4.11–4.13) ---
  'verdict.step': 'ШАГ',
  'verdict.nextStep': 'ДАЛЕЕ',
  'verdict.breakdown': 'РАЗБОР: ФАКТ → ЛОГИКА → ПРАВИЛО',
  'verdict.logic': 'ЛОГИКА',
  'verdict.sources': 'ИСТОЧНИКИ И МЕТОДИКА',
  'verdict.dataset': 'ДАТАСЕТ',
  'verdict.content': 'КОНТЕНТ',
  'verdict.method': 'МЕТОДИКА',
  'verdict.methodBody':
    'Исторический отрезок зафиксирован заранее: датасет, точка t₀ и продолжение проверяются по хэшу. Оценка — по логике, риску и дисциплине, а не по направлению цены.',
  'verdict.hash': 'ХЭШ БУДУЩЕГО',
  'verdict.dim.context': 'КОНТЕКСТ',
  'verdict.dim.evidence': 'ДОКАЗАТЕЛЬСТВА',
  'verdict.dim.action': 'ДЕЙСТВИЕ',
  'verdict.dim.risk': 'РИСК',
  'verdict.dim.discipline': 'ДИСЦИПЛИНА',
  // --- fixture: мета сценариев ---
  'scen.mvp-001.tf': '15M',
  'scen.mvp-002.tf': '5M',
  // --- fixture: короткие названия навыков (ряд из 4 слотов) ---
  'skill.risk-first.short': 'СНАЧАЛА РИСК',
  'skill.no-confirm.short': 'БЕЗ ОБЪЁМА — НЕТ',
  'skill.htf.short': 'СТАРШИЙ TF',
  'skill.news-noise.short': 'НОВОСТЬ ≠ СИГНАЛ',
  'skill.no-average.short': 'НЕ УСРЕДНЯЙ',
  'skill.flat-ok.short': 'ВНЕ РЫНКА',
  'skill.invalidate.short': 'ОТМЕНА ЗАРАНЕЕ',
  'skill.plan-profit.short': 'ПЛАН > ПРИБЫЛИ',
};

const EN: Record<string, string> = {
  'app.tagline': 'DECISION TRAINER · NOT AN EXCHANGE',
  'app.disclaimer':
    'The game gives no trading signals and promises no income. In-game resources cannot be withdrawn.',
  'app.loading': 'Loading the archive of market disasters…',
  'nav.home': 'HOME',
  'nav.academy': 'LEARN',
  'nav.arena': 'PRACTICE',
  'nav.bestiary': 'THREATS',
  'nav.more': 'MORE',
  'shell.scenarioProgress': 'SCENARIO',
  'shell.protocol': 'RULE',
  'arena.brief': 'BRIEFING',
  'arena.task': 'TASK',
  'arena.skills': 'SKILL CARDS',
  'arena.decisions': 'DECISION',
  'arena.confirm': 'LOCK DECISION',
  'arena.confirmHint': 'The future is hidden. After the lock — we open the archive.',
  'arena.step2': 'SECOND STEP',
  'arena.futureHidden': 'FUTURE HIDDEN',
  'arena.t0': 't0 · DECISION POINT',
  'arena.unskill': 'REMOVE CARD',
  'arena.pause': 'PAUSE',
  'arena.exit': 'ABANDON SCENARIO',
  'arena.exitHint': 'The market will wait. It is in no hurry at all.',
  'reveal.title': 'ARCHIVE OPENED',
  'reveal.play': 'PLAY CONSEQUENCES',
  'reveal.fact': 'MARKET FACT',
  'reveal.consequence': 'ACTION CONSEQUENCE',
  'reveal.quality': 'DECISION QUALITY',
  'reveal.next': 'NEXT HUNT',
  'reveal.review': 'BREAKDOWN',
  'reveal.rule': 'PORTABLE RULE',
  'verdict.agree': 'THE MARKET AGREED. THAT DOES NOT MEAN YOU WERE RIGHT.',
  'verdict.disagree': 'THE MARKET DISAGREED. THAT DOES NOT MEAN YOU WERE WRONG.',
  'states.loading': 'LOADING DATA',
  'states.loadingSub': 'The market is looking for an excuse. Wait.',
  'states.offline': 'NO CONNECTION',
  'states.offlineSub': 'Good news: the market is not going anywhere either.',
  'states.locked': 'LOCKED',
  'states.lockedSub': 'The entity still finds you an inconvenient victim.',
  'states.error': 'DATA FAILED TO LOAD',
  'states.errorSub': 'Even servers sometimes pretend everything is under control.',
  'states.empty': 'NOTHING HERE YET',
  'states.emptySub': 'Even panic starts with a blank sheet.',
  'states.saved': 'RESULT SAVED',
  'states.savedSub': 'The mistake now officially belongs to history.',
  'states.noTrade': 'FLAT',
  'states.noTradeSub': 'No position opened. No panic either.',
  'academy.title': 'ACADEMY',
  'academy.chapters': 'CHAPTERS',
  'academy.sub': 'Theory explains the principle. Practice checks whether you applied it in noise.',
  'bestiary.title': 'THREATS',
  'bestiary.sub': 'An entity is not an enemy to kill. It is pressure to keep out of the decision.',
  'journal.title': 'DECISION JOURNAL',
  'journal.sub': 'Not a scroll of errors, but history: patterns, strong skills, weak spots.',
  'tournament.title': 'TOURNAMENTS',
  'tournament.sub': 'One dataset for everyone. Win by quality; speed is tie-break only.',
  'market.title': 'MARKET',
  'market.sub': 'Cosmetics and content. Answers, scores and risk limits are not for sale.',
  'profile.title': 'PROFILE',
  'more.title': 'MORE',
  'settings.title': 'SETTINGS',
  'settings.sound': 'SOUND',
  'settings.reduceMotion': 'REDUCE MOTION',
  'settings.language': 'LANGUAGE',
  'home.title': 'HOME',
  'home.continue': 'CONTINUE THE HUNT',
  'home.daily': 'TODAY IN THE ARCHIVE',
  'common.back': 'BACK',
  'common.close': 'CLOSE',
  'common.retry': 'RETRY',
  'home.greet': 'The disaster archive is open. Pick where to be wrong with style today.',
  'home.resume': 'RESUME SCENARIO',
  'home.start': 'START THE HUNT',
  'home.scenarios': 'SCENARIOS',
  'home.sections': 'SECTIONS',
  'home.best': 'BEST',
  'academy.topic': 'TOPIC',
  'academy.train': 'TRAIN IN THE ARENA',
  'academy.linked': 'LINKED SKILLS',
  'bestiary.tell': 'TELL',
  'bestiary.counter': 'COUNTER',
  'bestiary.train': 'HUNT IN THE ARENA',
  'bestiary.mastered': 'MASTERED',
  'bestiary.seen': 'SPOTTED',
  'journal.patterns': 'REPEATING PATTERNS',
  'journal.history': 'DECISION HISTORY',
  'journal.repeat': 'REPLAY RECOMMENDATIONS',
  'journal.best': 'BEST QUALITY',
  'journal.fix': 'FIX',
  'journal.empty':
    'Empty so far: clear your first scenario and the journal will collect your patterns.',
  'tourn.join': 'ENTER',
  'tourn.joined': 'YOU ARE IN',
  'tourn.board': 'LEADERBOARD',
  'tourn.you': 'YOU',
  'tourn.note': 'Async: one dataset for everyone, win by quality. Speed is tie-break only.',
  'market.buy': 'BUY',
  'market.owned': 'OWNED',
  'market.balance': 'BALANCE',
  'market.noFunds': 'Not enough credits. The arena pays for quality, not for hope.',
  'market.bought': 'Bought. Cosmetics never affect decision quality — only the style of defeat.',
  'profile.stats': 'STATS',
  'profile.ach': 'ACHIEVEMENTS',
  'profile.completed': 'SCENARIOS CLOSED',
  'more.sections': 'ALL SECTIONS',
  'more.about': 'ABOUT THE TRAINER',
  'more.aboutBody':
    'SIGNAL ARENA is a decision-quality trainer on historical situations. Not an exchange, not signals, not an income promise.',
  'more.legal': 'LEGAL & DISCLAIMERS',
  'more.legalBody':
    'An educational trainer on historical data, not investment advice. In-game resources cannot be withdrawn.',
  'protocol.risk-first.title': 'Risk first',
  'protocol.risk-first.rule': 'Risk management is scored: size, stop, invalidation.',
  'protocol.evidence-only.title': 'Evidence only',
  'protocol.evidence-only.rule': 'The decision must rest on tab facts, not on noise.',
  'protocol.noise-quarantine.title': 'Noise quarantine',
  'protocol.noise-quarantine.rule': 'News and sentiment ignored: structure, volume and plan only.',
  'protocol.flat-ok.title': 'Flat is a decision',
  'protocol.flat-ok.rule': 'Staying out on a weak signal scores on par with a trade.',
  'protocol.save-system.title': 'Keep the system',
  'protocol.save-system.rule':
    'Loyalty to the trading plan is scored: no improvisation, no exceptions.',
  'protocol.after-loss.title': 'After a loss',
  'protocol.after-loss.rule': 'A post-stop series: pause, smaller risk, no revenge.',
  'protocol.confidence.title': 'Confidence check',
  'protocol.confidence.rule':
    'Calibration is scored: confidence must match the strength of evidence.',
  'arena.mode.title': 'PRACTICE',
  'arena.mode.hero': 'THE MARKET ALREADY HAPPENED. ONLY YOUR DECISION IS LEFT.',
  'arena.mode.formats': 'FORMAT',
  'arena.mode.format.free': 'Free drill',
  'arena.mode.format.freeBody': '1 scenario · 60–90 sec · matched to weak spots',
  'arena.mode.format.series': 'Series of 3',
  'arena.mode.format.seriesBody': 'One topic, rising difficulty · 8–12 min',
  'arena.mode.format.fix': 'Fix',
  'arena.mode.format.fixBody': 'Targeted work on a repeating mistake',
  'arena.mode.choose': 'Select',
  'arena.mode.rule': 'SESSION RULE',
  'arena.mode.ruleHint': 'AFFECTS SCORING',
  'arena.mode.focus': 'CONTENT FOCUS',
  'arena.mode.focus.all': 'ALL',
  'arena.mode.focus.structure': 'STRUCTURE',
  'arena.mode.focus.noise': 'NOISE',
  'arena.mode.focus.risk': 'RISK',
  'arena.mode.focus.psycho': 'PSYCHO',
  'arena.mode.focus.web3': 'WEB3',
  'arena.mode.start': 'Start →',
  'arena.mode.hashOk': 'HASH',
  'arena.brief.phase': 'PHASE',
  'arena.brief.timeframe': 'TIMEFRAME',
  'arena.brief.rule': 'RULE',
  'arena.brief.difficulty': 'DIFFICULTY',
  'arena.brief.preEntry': 'Pre-entry',
  'arena.brief.inPosition': 'In position · t₀+3',
  'arena.brief.situation': 'SITUATION · HISTORICAL',
  'arena.brief.tabs': 'SOURCES IN SCENARIO',
  'arena.brief.start': 'TO THE TASK →',
  'arena.pressure': 'PRESSURE',
  'arena.disclaimer': 'NOT FINANCIAL ADVICE · HISTORICAL DATA · OUTCOME ALREADY FIXED',
  'arena.skillsApplied': 'APPLIED',
  'arena.of': 'OF',
  'arena.moreSkills': 'MORE CARDS LIVE IN THE ACADEMY',
  'arena.catalog.title': 'SCENARIO SOURCES',
  'arena.catalog.sub':
    'Not all are needed in every task. Coins unlock data access, never the answer.',
  'arena.catalog.open': 'open',
  'arena.catalog.coins': 'coins',
  'arena.catalog.level': 'level',
  'arena.catalog.phaseOnly': 'in-position phase only',
  'arena.catalog.note':
    'Payment buys data access only. Correct answers, score boosts and extra risk are not for sale.',
  'arena.skill.type': 'TYPE',
  'arena.skill.mastery': 'MASTERY',
  'arena.skill.used': 'APPLIED',
  'arena.skill.times': 'TIMES',
  'arena.skill.avgQuality': 'AVG QUALITY',
  'arena.skill.studyIn': 'STUDIED IN',
  'arena.skill.toAcademy': 'To Academy',
  'arena.skill.apply': 'Apply',
  'arena.skill.kindName.reading': 'READING',
  'arena.skill.kindName.decision': 'DECISION',
  'arena.skill.kindName.protection': 'PROTECTION',
  'arena.skill.cardOf.reading': 'READING CARD',
  'arena.skill.cardOf.decision': 'DECISION CARD',
  'arena.skill.cardOf.protection': 'PROTECTION CARD',
  'arena.confirm.selected': 'SELECTED',
  'arena.confirm.changeable': 'can be changed before the lock',
  'arena.confirm.change': 'Change',
  'arena.confirm.lockNote': 'After the lock the continuation opens and changes become impossible.',
  'arena.reveal.layerFact': 'LAYER 1 · MARKET FACT',
  'arena.reveal.layerConsequence': 'LAYER 2 · CONSEQUENCE OF YOUR BEHAVIOUR',
  'arena.reveal.speed': 'SPEED',
  'arena.reveal.replay': '▶ REPLAY',
  'arena.reveal.frame': 'FRAME',
  'arena.volume.book': 'LIQUIDITY STRUCTURE',
  'arena.volume.asks': 'ASKS',
  'arena.volume.bids': 'BIDS',
  'arena.volume.wall': 'WHALE WALL',
  'arena.volume.wallBody': 'above the breakout level',
  'arena.volume.spread': 'SPREAD',
  'arena.volume.breakVol': 'BREAKOUT VOLUME',
  'arena.volume.toAvg': 'VS AVERAGE',
  'verdict.step': 'STEP',
  'verdict.nextStep': 'NEXT',
  'verdict.breakdown': 'BREAKDOWN: FACT → LOGIC → RULE',
  'verdict.logic': 'LOGIC',
  'verdict.sources': 'SOURCES & METHOD',
  'verdict.dataset': 'DATASET',
  'verdict.content': 'CONTENT',
  'verdict.method': 'METHOD',
  'verdict.methodBody':
    'The historical slice is fixed in advance: dataset, t₀ and continuation are hash-checked. Scoring rewards logic, risk and discipline — not price direction.',
  'verdict.hash': 'FUTURE HASH',
  'verdict.dim.context': 'CONTEXT',
  'verdict.dim.evidence': 'EVIDENCE',
  'verdict.dim.action': 'ACTION',
  'verdict.dim.risk': 'RISK',
  'verdict.dim.discipline': 'DISCIPLINE',
  'scen.mvp-001.tf': '15M',
  'scen.mvp-002.tf': '5M',
  'skill.risk-first.short': 'RISK FIRST',
  'skill.no-confirm.short': 'NO VOLUME — NO',
  'skill.htf.short': 'HIGHER TF',
  'skill.news-noise.short': 'NEWS ≠ SIGNAL',
  'skill.no-average.short': 'NEVER AVERAGE',
  'skill.flat-ok.short': 'STAY FLAT',
  'skill.invalidate.short': 'INVALIDATE EARLY',
  'skill.plan-profit.short': 'PLAN > PROFIT',
};

export const COPY: Record<Lang, Record<string, string>> = { ru: RU, en: EN };

/** Безопасное чтение копи: запрошенный язык → RU (первый язык MVP) → ключ. */
export function t(lang: Lang, key: string): string {
  return COPY[lang]?.[key] ?? COPY.ru[key] ?? key;
}
